import type { Dict } from "../i18n";
import type { DictX } from "../i18nX";

const t: Dict = {
  meta: { title: "Zuerich Airport Taxi - Taxi Aeropuerto de Zúrich & Servicio de Chófer Suiza", desc: "Traslados premium desde el aeropuerto de Zúrich (ZRH) a toda Suiza – precios fijos, conductores profesionales y seguimiento de vuelos. ¡Reserve su traslado en 1 minuto!" },
  topbar: "Zúrich · Traslados privados",
  nav: { routes: "Rutas", fleet: "Vehículos", gallery: "Galería", contact: "Contacto", book: "Reservar", home: "Inicio" },
  hero: {
    eyebrow: "Zúrich · Mercedes VIP", title1: "Traslados en Zúrich", title2: "en Mercedes VIP",
    sub: "Precio fijo · Chóferes cualificados · Seguimiento de vuelos · Asistencia 24/7",
    pills: ["Precio fijo", "Asistencia 24/7", "Confirmación inmediata"],
    cta1: "Reservar", cta2: "Rutas populares",
  },
  form: {
    title: "Solicitar un traslado",
    from: "Lugar de recogida", fromPh: "p. ej. Aeropuerto de Zúrich, Basilea …",
    to: "Destino", toPh: "p. ej. Zermatt, St. Moritz …",
    date: "Fecha", time: "Hora", pax: "Pasajeros", kids: "Niños",
    wa: "Solicitar por WhatsApp", callNow: "Llamar ahora", callSub: "Disponibles las 24 horas", mail: "Solicitar por correo",
    search: "Buscar", note: "Sillas infantiles gratis · Sin cargos extra",
  },
  msg: {
    title: "Solicitud de reserva – Traslado aeropuerto de Zúrich", contactTitle: "Solicitud de contacto – Sitio web",
    from: "Recogida", to: "Destino", date: "Fecha", time: "Hora", pax: "Pasajeros", kids: "Niños",
    name: "Nombre", email: "Correo", phone: "Teléfono", message: "Mensaje",
    subject: "Consulta – AirportTransfers Zúrich",
  },
  routesSec: {
    eyebrow: "Rutas", title: "Rutas populares",
    sub: "Nuestras rutas de traslado más reservadas – a precio fijo garantizado.",
    pageTitle: "Rutas",
    pageSub: "Todas las rutas desde el aeropuerto de Zúrich (ZRH) – precio fijo por vehículo, incl. 60 min. de espera.",
    from: "desde", origin: "Aeropuerto de Zúrich (ZRH)",
    all: "Ver todas", allNote: "¿Otro destino? Cubrimos toda Suiza – consúltenos.",
  },
  fleetSec: {
    eyebrow: "Vehículos", title: "Nuestra flota",
    sub: "Vehículos VIP cuidados y confortables para cada grupo.",
    pageTitle: "Vehículos",
    pageSub: "Todos los vehículos con chófer profesional, WiFi y agua mineral a bordo.",
    pax: "Pasajeros", bags: "Equipaje", cta: "Solicitar ahora",
    features: ["WiFi gratis", "Agua mineral", "Sillas infantiles bajo petición", "Seguimiento de vuelos"],
  },
  gallerySec: { eyebrow: "Galería", title: "Galería", pageTitle: "Galería", pageSub: "Impresiones de nuestros vehículos y trayectos.", all: "Ver todo" },
  reviewsSec: { eyebrow: "Opiniones", title: "Lo que dicen nuestros clientes", sub: "Experiencias reales de viajeros reales.", count: "opiniones", list: [
      { text: "Conductor puntual con cartel a la llegada, coche impecable. ¡Perfecto!", name: "Carmen G.", route: "ZRH → Zürich City", flag: "🇪🇸" },
      { text: "Precio fijo respetado a pesar del tráfico. Reserva por WhatsApp muy fácil.", name: "Javier M.", route: "ZRH → Luzern", flag: "🇪🇸" },
      { text: "El vuelo llegó con retraso y el conductor esperó sin coste extra.", name: "Lucía F.", route: "ZRH → Interlaken", flag: "🇲🇽" },
      { text: "Silla infantil lista como pedimos. Viaje tranquilo hasta Zermatt.", name: "Diego R.", route: "ZRH → Zermatt", flag: "🇪🇸" },
      { text: "Mercedes elegante, WiFi y agua a bordo. Un servicio realmente premium.", name: "Marta S.", route: "ZRH → Basel", flag: "🇦🇷" },
    ] },
  blogSec: {
    title: "Blog", pageSub: "Consejos de viaje, guías de rutas e información útil sobre traslados desde el aeropuerto de Zúrich.",
    read: "Leer más", minRead: "min de lectura", more: "Más artículos", back: "Todos los artículos", published: "Publicado el",
  },
  faqPage: {
    title: "Preguntas frecuentes", sub: "Respuestas a las preguntas clave sobre reserva, precios y funcionamiento.",
    list: [
      ["¿Cómo reservo un traslado?", "Lo más rápido: el asistente de reservas de esta web o directamente por WhatsApp. Normalmente recibirá la confirmación en 15 minutos."],
      ["¿Los precios son realmente fijos?", "Sí. El precio indicado al reservar es por vehículo y no cambia – independientemente del tráfico, el clima o la hora. No hay recargos nocturnos ni por equipaje."],
      ["¿Qué pasa si mi vuelo se retrasa?", "Seguimos su vuelo en tiempo real y ajustamos la recogida automáticamente. La espera tras el aterrizaje es gratuita."],
      ["¿Dónde encuentro a mi chófer en el aeropuerto?", "Su chófer le espera con un cartel con su nombre en la sala de llegadas (Meet & Greet) y le acompaña hasta el vehículo."],
      ["¿Cómo puedo pagar?", "Cómodamente en el vehículo: efectivo, tarjeta de crédito o TWINT. Los clientes de empresa pueden recibir una factura agrupada bajo petición."],
      ["¿Puedo cancelar gratis?", "Sí, hasta 24 horas antes de la recogida prevista la cancelación es gratuita con reembolso completo."],
      ["¿Hay sillas infantiles disponibles?", "Sí, portabebés y sillas infantiles se proporcionan gratis. Indique el número y la edad de los niños al reservar."],
      ["¿Transportan esquís y equipaje especial?", "Las bolsas de esquí viajan gratis (máx. 4 por vehículo). Es mejor avisar del equipaje voluminoso, como bolsas de golf o cochecitos, al reservar."],
    ],
  },
  booking: { title: "Reserva", steps: ["Ruta y hora", "Vehículo", "Contacto y pago"], route: "Ruta", choose: "Seleccione el destino …", next: "Continuar" },
  detail: {
    selectCar: "Elija su vehículo", summary: "Resumen del viaje",
    pickupLoc: "Lugar de recogida", dropoffLoc: "Destino", distance: "Distancia total", time: "Tiempo total",
    vehicle: "Vehículo seleccionado", priceNote: "Todos los precios incluyen IVA y tasas.", select: "Seleccionar",
    feats: ["Meet & Greet incluido", "Cancelación gratuita", "Espera gratuita", "Viaje seguro y fiable"],
    noticeTitle: "Aviso importante", noticeText: "Las reservas hechas menos de 2 horas antes de la recogida pueden no estar garantizadas en horas punta. Reserve con antelación.",
    payTitle: "Elija el método de pago",
    payOptions: [["TWINT", "Pago con TWINT en el vehículo"], ["Efectivo", "Pago en efectivo en el vehículo"], ["Tarjeta de crédito", "Pago con tarjeta en el vehículo"]],
    paxTitle: "Datos de los pasajeros", name: "Nombre", surname: "Apellidos", email: "Correo", phone: "Teléfono",
    baby: ["Portabebés", "Para bebés de 0–13 kg (aprox. 0–4 años)."],
    child: ["Silla infantil", "Para niños de 15–36 kg (aprox. 4–12 años)."],
    ski: ["Bolsa de esquí", "Transporte seguro del equipo (máx. 4 por vehículo)."],
    free: "Gratis", flight: "Número de vuelo", nameboard: "Cartel con nombre (opcional)", luggage: "Equipaje",
    notes: "Mensaje al chófer (opcional)", accept: "Acepto las condiciones de reserva.", back: "Atrás",
    continueWa: "Solicitar la reserva por WhatsApp", continueMail: "…o solicitar por correo",
    confirmNote: "Normalmente recibirá la confirmación en 15 minutos.", total: "Total",
    notFound: "Ruta no encontrada.", allRoutes: "Todas las rutas",
  },
  kontakt: {
    title: "Contacto", formTitle: "Enviar un mensaje",
    name: "Su nombre", email: "Correo", phone: "Teléfono", message: "Mensaje",
    send: "Enviar", orMail: "…o escríbanos directamente por correo", infoTitle: "Contáctenos",
    lblPhone: "Teléfono", lblEmail: "Correo", lblWa: "WhatsApp", lblAddress: "Dirección",
    lblHours: "Horario de oficina", always: "Disponibles las 24 horas",
  },
  footer: {
    popular: "Rutas populares", aboutLink: "Sobre nosotros", information: "Información",
    about: "Traslados VIP en Mercedes en Zúrich. Precios fijos, chóferes cualificados y seguimiento de vuelos – 24/7.",
    follow: "Síganos", explore: "Explorar", company: "Empresa", support: "Asistencia",
    callUs: "Llámenos", writeUs: "Escríbanos", address: "Dirección",
    about2: "Sobre nosotros", faq: "Preguntas frecuentes", rights: "Todos los derechos reservados.", watermark: "Zúrich",
  },
};

const tx: DictX = {
  nav: { destinations: "Destinos", prices: "Precios", events: "Eventos" },
  heroBadges: ["Cancelación gratuita", "Asistencia 24/7", "Seguimiento de vuelos", "Precio fijo"],
  heroRating: { score: "Excelente · 4.8/5", sub: "La elección de los viajeros en el aeropuerto de Zúrich" },
  howSec: {
    eyebrow: "Cómo funciona", title: "Reserve en tres sencillos pasos",
    steps: [
      ["Introduzca la ruta y elija el vehículo", "Indique recogida, destino y hora – luego elija el vehículo adecuado."],
      ["Complete su reserva", "Añada sus datos y reciba la confirmación con todos los detalles."],
      ["Encuentre a su chófer", "Su chófer le espera con un cartel con su nombre – la espera está incluida."],
    ],
    cta: "Obtener precio",
  },
  faqSec: { eyebrow: "FAQ", title: "Preguntas frecuentes", sub: "Todo lo esencial sobre su reserva, de un vistazo.", all: "Ver todas las preguntas" },
  hourly: {
    tabTransfer: "Traslado", tabHourly: "Por horas", duration: "Duración", hoursShort: "horas",
    note: "Chófer y vehículo a su disposición – ideal para reuniones, eventos y visitas por la ciudad.",
    cta: "Ver precios", bookingLabel: "Alquiler por horas",
    bookingNote: (h: string) => `Reserva por horas: ${h} horas – chófer a disposición`,
  },
  stops: { add: "Añadir una parada", ph: "Parada – dirección", remove: "Eliminar", label: "Paradas intermedias:" },
  busy: { title: "Nuestros vehículos están ocupados a esta hora", text: "Ya hay un traslado programado en esta franja. Elija otra hora o contáctenos: encontraremos una solución.", cta: "Hablar con atención al cliente", next: "Próxima hora libre:" },
  night: { title: "Reserva nocturna de última hora no disponible", text: "En horario nocturno no aceptamos automáticamente viajes con menos de 2 horas de antelación. Elija una hora posterior o contáctenos directamente: comprobaremos la disponibilidad personalmente.", earliest: "Lo antes posible a partir de:" },
  done: { title: "¡Solicitud enviada!", body: (r: string) => `Su solicitud de traslado ${r} se ha creado y abierto en WhatsApp o por correo. Envíe el mensaje – normalmente confirmamos en 15 minutos.`, hint: "¡Gracias por su solicitud! Revise también su bandeja de entrada o carpeta de spam.", payment: "Método de pago", home: "Volver al inicio" },
  dest: {
    crumb: "Destinos",
    pageTitle: "Traslados por toda Suiza",
    pageSub: "Del aeropuerto de Zúrich a cada ciudad y pueblo de montaña. Elija su destino o reserve directamente.",
    popular: "Lugares populares", searchPh: "Buscar un lugar …",
    fixed: "desde CHF", onRequest: "Precio a consultar",
    hero: (n: string) => `Traslado aeropuerto ${n}`,
    heroSub: (n: string) => `Servicio de chófer privado y traslado aeroportuario hacia y desde ${n}. Precio fijo por vehículo, chóferes cualificados y seguimiento de vuelos – las 24 horas.`,
    chips: ["Precio fijo", "Seguimiento de vuelos", "24/7", "Chóferes autorizados"],
    calc: "Calcular precio",
    f1: ["Precios fijos", "Su precio queda fijado antes del viaje – sin sorpresas."],
    f2: ["Siempre puntuales", "Seguimos su vuelo y ajustamos la hora de recogida."],
    f3: ["Seguro y autorizado", "Chóferes cualificados, Mercedes en perfecto estado."],
    vehiclesFor: (n: string) => `Vehículos para ${n}`,
    routeKnown: (n: string, p: string) => `Precio fijo aeropuerto de Zúrich → ${n}: desde CHF ${p} por vehículo.`,
    routeDetail: "Ver la ruta en detalle",
    seo: (n: string, r: string) => [
      [`Taxi de aeropuerto a ${n} a precio fijo`, `¿Busca un traslado fiable a ${n}? Reserve con nosotros su traslado privado hacia y desde el aeropuerto de Zúrich (ZRH) a un precio fijo garantizado por vehículo. Sin taxímetro ni recargos ocultos: el precio queda fijado en el momento de la reserva, sin importar el tráfico ni la hora.`],
      [`Del aeropuerto de Zúrich (ZRH) a ${n}`, `Su chófer le espera con un cartel con su nombre en la sala de llegadas (Meet & Greet) y le ayuda con el equipaje. Para el regreso desde ${r}, calculamos el tráfico y los tiempos de facturación para que llegue al aeropuerto relajado y a tiempo.`],
      [`24/7 con seguimiento de vuelos`, `Seguimos su vuelo en tiempo real. Si el avión aterriza antes o después, la hora de recogida se ajusta automáticamente – la espera tras el aterrizaje está incluida en el precio fijo. Operamos los 365 días del año.`],
      [`El vehículo adecuado para cada ocasión`, `Viaje de negocios, vacaciones en familia o semana de esquí: desde la Business Class hasta la furgoneta espaciosa de hasta 7 plazas, encontrará el vehículo idóneo para su traslado a ${n}. Sillas infantiles y portabebés gratis.`],
    ],
    faqTitle: (n: string) => `Preguntas frecuentes sobre el traslado a ${n}`,
    faq: (n: string) => [
      [`¿Cuánto cuesta un taxi de aeropuerto a ${n}?`, `El precio es fijo por vehículo y depende de la distancia desde el aeropuerto de Zúrich y de la clase de vehículo. Pida presupuesto en segundos – recibirá el precio fijo antes del viaje.`],
      [`¿Cómo reservo mi traslado a ${n}?`, `Introduzca su dirección, elija fecha y hora, añada su número de vuelo – listo. La reserva lleva menos de un minuto, online o por WhatsApp.`],
      ["¿El seguimiento de vuelos está incluido?", "Sí. Seguimos cada vuelo y ajustamos automáticamente la hora de recogida. La espera tras el aterrizaje está incluida en el precio."],
      ["¿Puedo cancelar gratis?", "Sí, la cancelación es gratuita hasta 24 horas antes de la recogida prevista."],
    ],
    more: "Más destinos", all: "Todos los lugares",
    ctaTitle: "¿Listo para llegar relajado?",
    ctaSub: "Reciba en segundos un precio fijo y transparente – sin necesidad de cuenta.",
    ctaBtn: "Reservar",
  },
  prices: {
    crumb: "Precios", title: "Precios fijos y transparentes",
    sub: "Cada viaje a precio fijo por vehículo – incl. 60 min. de espera en el aeropuerto, Meet & Greet y seguimiento de vuelos. Sin costes ocultos.",
    f1: ["Precio fijo garantizado", "El precio queda fijado al reservar."],
    f2: ["Seguimiento de vuelos", "Espera gratuita en caso de retraso."],
    f3: ["Todo incluido", "Impuestos, peajes y Meet & Greet incluidos."],
    classesTitle: "Nuestras clases de vehículos y precios",
    from: "desde", perVehicle: "por vehículo", book: "Reservar",
    tableTitle: "Precios fijos por ruta",
    tableSub: "Todas las rutas desde el aeropuerto de Zúrich (ZRH) – precio por vehículo, no por persona.",
    colDest: "Destino", colKm: "Distancia", colDur: "Duración",
    destTitle: "Precios por destino",
    destSub: "Más de 250 lugares en Suiza y regiones vecinas. Elija su destino para ver los detalles.",
    request: "A consultar",
  },
  events: {
    crumb: "Eventos", title: "Eventos en Suiza – su traslado privado",
    sub: "Reserve su chófer para las ferias, festivales y viajes panorámicos más conocidos de Suiza.",
    all: "Todos", book: "Reservar traslado",
  },
};

export const es = { t, tx };
