import type { Dict } from "../i18n";
import type { DictX } from "../i18nX";

const t: Dict = {
  meta: { title: "Zuerich Airport Taxi - Taxi Aéroport de Zurich & Service Chauffeur Suisse", desc: "Transferts aéroport premium depuis Zurich (ZRH) dans toute la Suisse – prix fixes, chauffeurs professionnels et suivi des vols. Réservez votre transfert en 1 minute !" },
  topbar: "Zurich · Transferts privés",
  nav: { routes: "Trajets", fleet: "Véhicules", gallery: "Galerie", contact: "Contact", book: "Réserver", home: "Accueil" },
  hero: {
    eyebrow: "Zurich · Mercedes VIP", title1: "Transferts Zurich", title2: "en Mercedes VIP",
    sub: "Prix fixe · Chauffeurs formés · Suivi des vols · Assistance 24h/24",
    pills: ["Prix fixe", "Assistance 24h/24", "Confirmation immédiate"],
    cta1: "Réserver", cta2: "Trajets populaires",
  },
  form: {
    title: "Demander un transfert",
    from: "Lieu de prise en charge", fromPh: "p. ex. Aéroport de Zurich, Bâle …",
    to: "Destination", toPh: "p. ex. Zermatt, St-Moritz …",
    date: "Date", time: "Heure", pax: "Passagers", kids: "Enfants",
    wa: "Demander via WhatsApp", callNow: "Appeler", callSub: "Joignables 24h/24", mail: "Demander par e-mail",
    search: "Rechercher", note: "Sièges enfants gratuits · Aucun frais supplémentaire",
  },
  msg: {
    title: "Demande de réservation – Transfert aéroport de Zurich", contactTitle: "Demande de contact – Site web",
    from: "Prise en charge", to: "Destination", date: "Date", time: "Heure", pax: "Passagers", kids: "Enfants",
    name: "Nom", email: "E-mail", phone: "Téléphone", message: "Message",
    subject: "Demande – AirportTransfers Zurich",
  },
  routesSec: {
    eyebrow: "Trajets", title: "Trajets populaires",
    sub: "Nos trajets de transfert aéroport les plus réservés – à prix fixe garanti.",
    pageTitle: "Trajets",
    pageSub: "Tous les trajets depuis l'aéroport de Zurich (ZRH) – prix fixe par véhicule, 60 min. d'attente incluses.",
    from: "dès", origin: "Aéroport de Zurich (ZRH)",
    all: "Tout voir", allNote: "Une autre destination ? Nous desservons toute la Suisse – contactez-nous.",
  },
  fleetSec: {
    eyebrow: "Véhicules", title: "Notre flotte",
    sub: "Des véhicules VIP soignés et confortables pour chaque groupe.",
    pageTitle: "Véhicules",
    pageSub: "Tous les véhicules avec chauffeur professionnel, WiFi et eau minérale à bord.",
    pax: "Passagers", bags: "Bagages", cta: "Demander maintenant",
    features: ["WiFi gratuit", "Eau minérale", "Sièges enfants sur demande", "Suivi des vols"],
  },
  gallerySec: { eyebrow: "Galerie", title: "Galerie", pageTitle: "Galerie", pageSub: "Impressions de nos véhicules et de nos trajets.", all: "Tout voir" },
  reviewsSec: { eyebrow: "Avis clients", title: "Ce que disent nos clients", sub: "Des expériences réelles de vrais voyageurs.", count: "avis", list: [
      { text: "Chauffeur ponctuel, pancarte à l'arrivée, voiture impeccable. Parfait.", name: "Camille D.", route: "ZRH → Genève", flag: "🇫🇷" },
      { text: "Prix fixe respecté malgré les bouchons. Réservation WhatsApp très simple.", name: "Nicolas L.", route: "ZRH → Lausanne", flag: "🇫🇷" },
      { text: "Vol retardé de 45 minutes – le chauffeur attendait sans supplément.", name: "Sophie M.", route: "ZRH → Montreux", flag: "🇨🇭" },
      { text: "Siège enfant installé comme demandé. Trajet serein jusqu'à Verbier.", name: "Julien P.", route: "ZRH → Verbier", flag: "🇫🇷" },
      { text: "Mercedes très confortable, chauffeur discret. Idéal pour nos clients d'affaires.", name: "Isabelle R.", route: "ZRH → Fribourg", flag: "🇧🇪" },
    ] },
  blogSec: {
    title: "Blog", pageSub: "Conseils de voyage, guides des trajets et informations utiles sur les transferts depuis l'aéroport de Zurich.",
    read: "Lire la suite", minRead: "min de lecture", more: "Autres articles", back: "Tous les articles", published: "Publié le",
  },
  faqPage: {
    title: "Questions fréquentes", sub: "Les réponses aux questions essentielles sur la réservation, les prix et le déroulement.",
    list: [
      ["Comment réserver un transfert ?", "Le plus rapide : l'assistant de réservation sur ce site ou directement via WhatsApp. Vous recevez en général votre confirmation sous 15 minutes."],
      ["Les prix sont-ils vraiment fixes ?", "Oui. Le prix annoncé à la réservation s'applique par véhicule et ne change pas – quels que soient le trafic, la météo ou l'heure. Aucun supplément de nuit ni de bagages."],
      ["Que se passe-t-il si mon vol est retardé ?", "Nous suivons votre vol en temps réel et ajustons automatiquement l'heure de prise en charge. L'attente après l'atterrissage est gratuite."],
      ["Où retrouver mon chauffeur à l'aéroport ?", "Votre chauffeur vous attend avec une pancarte à votre nom directement dans le hall des arrivées (Meet & Greet) et vous accompagne jusqu'au véhicule."],
      ["Comment puis-je payer ?", "En toute simplicité dans le véhicule : espèces, carte de crédit ou TWINT. Les entreprises peuvent recevoir une facture groupée sur demande."],
      ["Puis-je annuler gratuitement ?", "Oui, jusqu'à 24 heures avant la prise en charge prévue, l'annulation est gratuite et intégralement remboursée."],
      ["Des sièges enfants sont-ils disponibles ?", "Oui, coques bébé et sièges enfants sont fournis gratuitement. Indiquez simplement le nombre et l'âge des enfants lors de la réservation."],
      ["Transportez-vous skis et bagages spéciaux ?", "Les housses à skis voyagent gratuitement (max. 4 par véhicule). Signalez de préférence les bagages volumineux (sacs de golf, poussettes) à la réservation."],
    ],
  },
  booking: { title: "Réservation", steps: ["Trajet et horaire", "Véhicule", "Contact et paiement"], route: "Trajet", choose: "Veuillez choisir la destination …", next: "Continuer" },
  detail: {
    selectCar: "Choisissez votre véhicule", summary: "Récapitulatif du trajet",
    pickupLoc: "Lieu de prise en charge", dropoffLoc: "Destination", distance: "Distance totale", time: "Durée totale",
    vehicle: "Véhicule sélectionné", priceNote: "Tous les prix incluent la TVA et les frais.", select: "Sélectionner",
    feats: ["Meet & Greet inclus", "Annulation gratuite", "Attente gratuite", "Trajet sûr et fiable"],
    noticeTitle: "Remarque importante", noticeText: "Les réservations effectuées moins de 2 heures avant la prise en charge ne peuvent pas être garanties aux heures de pointe. Merci de réserver au plus tôt.",
    payTitle: "Choisissez le mode de paiement",
    payOptions: [["TWINT", "Paiement par TWINT dans le véhicule"], ["Espèces", "Paiement en espèces dans le véhicule"], ["Carte de crédit", "Paiement par carte dans le véhicule"]],
    paxTitle: "Données des passagers", name: "Prénom", surname: "Nom", email: "E-mail", phone: "Téléphone",
    baby: ["Coque bébé", "Pour les tout-petits 0–13 kg (env. 0–4 ans)."],
    child: ["Siège enfant", "Pour les enfants 15–36 kg (env. 4–12 ans)."],
    ski: ["Housse à skis", "Transport sûr de l'équipement (max. 4 par véhicule)."],
    free: "Gratuit", flight: "Numéro de vol", nameboard: "Pancarte nominative (facultatif)", luggage: "Bagages",
    notes: "Message au chauffeur (facultatif)", accept: "J'accepte les conditions de réservation.", back: "Retour",
    continueWa: "Demander la réservation via WhatsApp", continueMail: "…ou demander par e-mail",
    confirmNote: "Vous recevez en général votre confirmation sous 15 minutes.", total: "Total",
    notFound: "Trajet introuvable.", allRoutes: "Tous les trajets",
  },
  kontakt: {
    title: "Contact", formTitle: "Envoyer un message",
    name: "Votre nom", email: "E-mail", phone: "Téléphone", message: "Message",
    send: "Envoyer", orMail: "…ou écrivez-nous directement par e-mail", infoTitle: "Contactez-nous",
    lblPhone: "Téléphone", lblEmail: "E-mail", lblWa: "WhatsApp", lblAddress: "Adresse",
    lblHours: "Horaires de bureau", always: "Joignables 24h/24",
  },
  footer: {
    popular: "Trajets populaires", aboutLink: "À propos", information: "Informations",
    about: "Transferts VIP en Mercedes à Zurich. Prix fixes, chauffeurs formés et suivi des vols – 24h/24.",
    follow: "Suivez-nous", explore: "Découvrir", company: "Entreprise", support: "Assistance",
    callUs: "Appelez-nous", writeUs: "Écrivez-nous", address: "Adresse",
    about2: "À propos", faq: "Questions fréquentes", rights: "Tous droits réservés.", watermark: "Zurich",
  },
};

const tx: DictX = {
  nav: { destinations: "Destinations", prices: "Tarifs", events: "Événements" },
  heroBadges: ["Annulation gratuite", "Assistance 24h/24", "Suivi des vols", "Prix fixe"],
  heroRating: { score: "Excellent · 4.8/5", sub: "Plébiscité par les voyageurs à l'aéroport de Zurich" },
  howSec: {
    eyebrow: "Comment ça marche", title: "Réservez en trois étapes simples",
    steps: [
      ["Saisissez le trajet et choisissez le véhicule", "Indiquez la prise en charge, la destination et l'horaire – puis choisissez le véhicule adapté."],
      ["Finalisez votre réservation", "Ajoutez vos coordonnées et recevez la confirmation avec tous les détails."],
      ["Retrouvez votre chauffeur", "Votre chauffeur vous attend avec une pancarte à votre nom – attente incluse."],
    ],
    cta: "Obtenir un prix",
  },
  faqSec: { eyebrow: "FAQ", title: "Questions fréquentes", sub: "L'essentiel sur votre réservation, en un coup d'œil.", all: "Voir toutes les questions" },
  hourly: {
    tabTransfer: "Transfert", tabHourly: "À l'heure", duration: "Durée", hoursShort: "heures",
    note: "Chauffeur et véhicule à votre disposition – idéal pour rendez-vous, événements et visites de ville.",
    cta: "Voir les tarifs", bookingLabel: "Location à l'heure",
    bookingNote: (h: string) => `Réservation à l'heure : ${h} heures – chauffeur à disposition`,
  },
  stops: { add: "Ajouter un arrêt", ph: "Arrêt – adresse", remove: "Supprimer", label: "Arrêts intermédiaires :" },
  done: { title: "Demande envoyée !", body: (r: string) => `Votre demande de transfert ${r} a été créée et ouverte dans WhatsApp ou par e-mail. Envoyez le message – nous confirmons en général sous 15 minutes.`, hint: "Merci pour votre demande ! Pensez à vérifier votre boîte de réception ou vos spams.", payment: "Mode de paiement", home: "Retour à l'accueil" },
  dest: {
    crumb: "Destinations",
    pageTitle: "Transferts dans toute la Suisse",
    pageSub: "De l'aéroport de Zurich vers chaque ville et village de montagne. Choisissez votre destination ou réservez directement.",
    popular: "Lieux populaires", searchPh: "Rechercher un lieu …",
    fixed: "dès CHF", onRequest: "Prix sur demande",
    hero: (n: string) => `Transfert aéroport ${n}`,
    heroSub: (n: string) => `Service de chauffeur privé et transfert aéroport vers et depuis ${n}. Prix fixe par véhicule, chauffeurs formés et suivi des vols – 24h/24.`,
    chips: ["Prix fixe", "Suivi des vols", "24h/24", "Chauffeurs agréés"],
    calc: "Calculer le prix",
    f1: ["Prix fixes", "Votre prix est fixé avant le trajet – sans surprise."],
    f2: ["Toujours à l'heure", "Nous suivons votre vol et ajustons l'heure de prise en charge."],
    f3: ["Sûr et agréé", "Chauffeurs formés, Mercedes parfaitement entretenues."],
    vehiclesFor: (n: string) => `Véhicules pour ${n}`,
    routeKnown: (n: string, p: string) => `Prix fixe aéroport de Zurich → ${n} : dès CHF ${p} par véhicule.`,
    routeDetail: "Voir le trajet en détail",
    seo: (n: string, r: string) => [
      [`Taxi aéroport ${n} à prix fixe`, `Vous cherchez un transfert aéroport fiable vers ${n} ? Réservez chez nous votre transfert privé vers et depuis l'aéroport de Zurich (ZRH) à un prix fixe garanti par véhicule. Pas de taximètre, pas de supplément caché : le prix est fixé dès la réservation, quels que soient le trafic ou l'heure.`],
      [`De l'aéroport de Zurich (ZRH) à ${n}`, `Votre chauffeur vous attend avec une pancarte à votre nom directement dans le hall des arrivées (Meet & Greet) et vous aide avec les bagages. Pour le retour depuis ${r}, nous intégrons le trafic et les délais d'enregistrement afin que vous arriviez à l'aéroport détendu et à l'heure.`],
      [`24h/24 avec suivi des vols`, `Nous suivons votre vol en temps réel. Si l'avion atterrit plus tôt ou plus tard, l'heure de prise en charge s'ajuste automatiquement – l'attente après l'atterrissage est incluse dans le prix fixe. Notre service fonctionne 365 jours par an.`],
      [`Le bon véhicule pour chaque occasion`, `Voyage d'affaires, vacances en famille ou séjour au ski : de la Business Class au van spacieux jusqu'à 7 places, vous trouverez le véhicule adapté à votre transfert vers ${n}. Sièges enfants et coques bébé sont gratuits.`],
    ],
    faqTitle: (n: string) => `Questions fréquentes sur le transfert vers ${n}`,
    faq: (n: string) => [
      [`Combien coûte un taxi aéroport pour ${n} ?`, `Le prix est fixe par véhicule et dépend de la distance depuis l'aéroport de Zurich ainsi que de la classe de véhicule. Demandez un devis en quelques secondes – vous recevez le prix fixe avant le trajet.`],
      [`Comment réserver mon transfert vers ${n} ?`, `Saisissez votre adresse, choisissez la date et l'heure, ajoutez votre numéro de vol – c'est fait. La réservation prend moins d'une minute, en ligne ou via WhatsApp.`],
      ["Le suivi des vols est-il inclus ?", "Oui. Nous suivons chaque vol et ajustons automatiquement l'heure de prise en charge. L'attente après l'atterrissage est incluse dans le prix."],
      ["Puis-je annuler gratuitement ?", "Oui, l'annulation est gratuite jusqu'à 24 heures avant la prise en charge prévue."],
    ],
    more: "Autres destinations", all: "Tous les lieux",
    ctaTitle: "Prêt à arriver détendu ?",
    ctaSub: "Recevez en quelques secondes un prix fixe et transparent – sans créer de compte.",
    ctaBtn: "Réserver",
  },
  prices: {
    crumb: "Tarifs", title: "Des prix fixes et transparents",
    sub: "Chaque trajet à prix fixe par véhicule – 60 min. d'attente à l'aéroport, Meet & Greet et suivi des vols inclus. Aucun frais caché.",
    f1: ["Prix fixe garanti", "Le prix est verrouillé à la réservation."],
    f2: ["Suivi des vols", "Attente gratuite en cas de retard."],
    f3: ["Tout inclus", "Taxes, péages et Meet & Greet compris."],
    classesTitle: "Nos classes de véhicules et leurs tarifs",
    from: "dès", perVehicle: "par véhicule", book: "Réserver",
    tableTitle: "Prix fixes par trajet",
    tableSub: "Tous les trajets depuis l'aéroport de Zurich (ZRH) – prix par véhicule, pas par personne.",
    colDest: "Destination", colKm: "Distance", colDur: "Durée",
    destTitle: "Tarifs par destination",
    destSub: "Plus de 250 lieux en Suisse et dans les régions voisines. Choisissez votre destination pour les détails.",
    request: "Sur demande",
  },
  events: {
    crumb: "Événements", title: "Événements en Suisse – votre transfert privé",
    sub: "Réservez votre chauffeur pour les foires, festivals et trajets panoramiques les plus renommés de Suisse.",
    all: "Tous", book: "Réserver le transfert",
  },
};

export const fr = { t, tx };
