import type { Dict } from "../i18n";
import type { DictX } from "../i18nX";

const t: Dict = {
  meta: { title: "Zuerich Airport Taxi - Taksi zračna luka Zürich & usluga vozača Švicarska", desc: "Premium transferi iz zračne luke Zürich (ZRH) po cijeloj Švicarskoj – fiksne cijene, profesionalni vozači i praćenje letova. Rezervirajte transfer u 1 minuti!" },
  topbar: "Zürich · Privatni transferi",
  nav: { routes: "Rute", fleet: "Vozila", gallery: "Galerija", contact: "Kontakt", book: "Rezerviraj odmah", home: "Početna" },
  hero: {
    eyebrow: "Zürich · VIP Mercedes", title1: "Transferi u Zürichu", title2: "u VIP Mercedesu",
    sub: "Fiksna cijena · Obučeni vozači · Praćenje letova · Podrška 24/7",
    pills: ["Fiksna cijena", "Podrška 24/7", "Trenutna potvrda"],
    cta1: "Rezerviraj odmah", cta2: "Popularne rute",
  },
  form: {
    title: "Zatražite transfer",
    from: "Mjesto preuzimanja", fromPh: "npr. zračna luka Zürich, Basel …",
    to: "Odredište", toPh: "npr. Zermatt, St. Moritz …",
    date: "Datum", time: "Vrijeme", pax: "Putnici", kids: "Djeca",
    wa: "Zatražite putem WhatsAppa", callNow: "Nazovite odmah", callSub: "Dostupni 24 sata dnevno", mail: "Zatražite e-poštom",
    search: "Pretraži", note: "Besplatne dječje sjedalice · Bez dodatnih troškova",
  },
  msg: {
    title: "Zahtjev za rezervaciju – transfer iz zračne luke Zürich", contactTitle: "Zahtjev za kontakt – web-stranica",
    from: "Preuzimanje", to: "Odredište", date: "Datum", time: "Vrijeme", pax: "Putnici", kids: "Djeca",
    name: "Ime", email: "E-pošta", phone: "Telefon", message: "Poruka",
    subject: "Upit – AirportTransfers Zürich",
  },
  routesSec: {
    eyebrow: "Rute", title: "Popularne rute",
    sub: "Naše najčešće rezervirane rute transfera – po zajamčenoj fiksnoj cijeni.",
    pageTitle: "Rute",
    pageSub: "Sve rute iz zračne luke Zürich (ZRH) – fiksna cijena po vozilu, uklj. 60 min. čekanja.",
    from: "od", origin: "Zračna luka Zürich (ZRH)",
    all: "Prikaži sve", allNote: "Drugo odredište? Vozimo po cijeloj Švicarskoj – pitajte nas.",
  },
  fleetSec: {
    eyebrow: "Vozila", title: "Naša flota",
    sub: "Njegovana, udobna VIP vozila za grupe svih veličina.",
    pageTitle: "Vozila",
    pageSub: "Sva vozila s profesionalnim vozačem, WiFi-jem i mineralnom vodom.",
    pax: "Putnici", bags: "Prtljaga", cta: "Pitajte odmah",
    features: ["Besplatan WiFi", "Mineralna voda", "Dječje sjedalice na zahtjev", "Praćenje letova"],
  },
  gallerySec: { eyebrow: "Galerija", title: "Galerija", pageTitle: "Galerija", pageSub: "Dojmovi iz naših vozila i s naših vožnji.", all: "Prikaži sve" },
  reviewsSec: { eyebrow: "Recenzije", title: "Što kažu naši gosti", sub: "Prava iskustva pravih putnika.", count: "recenzija", list: [
      { text: "Vozač je čekao s pločicom, auto besprijekoran. Rezervacija WhatsAppom u minuti.", name: "Ivan H.", route: "ZRH → Zürich City", flag: "🇭🇷" },
      { text: "Let je kasnio – vozač je čekao bez doplate. Pouzdana usluga od početka do kraja.", name: "Petra M.", route: "ZRH → Luzern", flag: "🇭🇷" },
      { text: "Fiksna cijena ispoštovana unatoč gužvi. Najbolji transfer u Švicarskoj.", name: "Luka B.", route: "ZRH → Bern", flag: "🇭🇷" },
      { text: "Dječja sjedalica spremna kako smo tražili. Miran put do Interlakena.", name: "Ana V.", route: "ZRH → Interlaken", flag: "🇭🇷" },
      { text: "Udoban Mercedes, diskretan vozač. Idealno za poslovna putovanja.", name: "Marko T.", route: "ZRH → Zug", flag: "🇭🇷" },
    ] },
  blogSec: {
    title: "Blog", pageSub: "Savjeti za putovanja, vodiči po rutama i korisne informacije o transferima iz zračne luke Zürich.",
    read: "Pročitaj više", minRead: "min. čitanja", more: "Ostali članci", back: "Svi članci", published: "Objavljeno",
  },
  faqPage: {
    title: "Česta pitanja", sub: "Odgovori na najvažnija pitanja o rezervaciji, cijenama i tijeku vožnje.",
    list: [
      ["Kako rezervirati transfer?", "Najbrže putem asistenta za rezervacije na ovoj stranici ili izravno putem WhatsAppa. Potvrdu obično dobivate unutar 15 minuta."],
      ["Jesu li cijene doista fiksne?", "Da. Cijena navedena pri rezervaciji vrijedi po vozilu i ne mijenja se – bez obzira na promet, vrijeme ili doba dana. Nema noćnih doplata ni doplata za prtljagu."],
      ["Što ako moj let kasni?", "Pratimo vaš let u stvarnom vremenu i automatski prilagođavamo vrijeme preuzimanja. Čekanje nakon slijetanja je besplatno."],
      ["Gdje ću naći vozača u zračnoj luci?", "Vaš vozač čeka vas s pločicom s vašim imenom izravno u dolaznoj dvorani (Meet & Greet) i prati vas do vozila."],
      ["Kako mogu platiti?", "Jednostavno u vozilu: gotovinom, karticom ili TWINT-om. Poslovni klijenti na zahtjev dobivaju zbirni račun."],
      ["Mogu li besplatno otkazati?", "Da, do 24 sata prije planiranog preuzimanja otkazivanje je besplatno uz puni povrat novca."],
      ["Jesu li dostupne dječje sjedalice?", "Da, nosiljke za bebe i dječje sjedalice osiguravamo besplatno. Samo navedite broj i dob djece pri rezervaciji."],
      ["Prevozite li skije i posebnu prtljagu?", "Torbe za skije prevozimo besplatno (najviše 4 po vozilu). Glomaznu prtljagu, poput torbi za golf ili kolica, najbolje je najaviti pri rezervaciji."],
    ],
  },
  booking: { title: "Rezervacija", steps: ["Ruta i vrijeme", "Vozilo", "Kontakt i plaćanje"], route: "Ruta", choose: "Odaberite odredište …", next: "Dalje" },
  detail: {
    selectCar: "Odaberite vozilo", summary: "Pregled vožnje",
    pickupLoc: "Mjesto preuzimanja", dropoffLoc: "Odredište", distance: "Ukupna udaljenost", time: "Ukupno vrijeme",
    vehicle: "Odabrano vozilo", priceNote: "Sve cijene uključuju PDV i pristojbe.", select: "Odaberi",
    feats: ["Meet & Greet uključen", "Besplatno otkazivanje", "Besplatno čekanje", "Sigurna i pouzdana vožnja"],
    noticeTitle: "Važna napomena", noticeText: "Rezervacije napravljene manje od 2 sata prije preuzimanja ne mogu se jamčiti u vršnim satima. Molimo rezervirajte na vrijeme.",
    payTitle: "Odaberite način plaćanja",
    payOptions: [["TWINT", "Plaćanje TWINT-om u vozilu"], ["Gotovina", "Plaćanje gotovinom u vozilu"], ["Kreditna kartica", "Plaćanje karticom u vozilu"]],
    paxTitle: "Podaci o putnicima", name: "Ime", surname: "Prezime", email: "E-pošta", phone: "Telefon",
    baby: ["Nosiljka za bebe", "Za bebe 0–13 kg (oko 0–4 godine)."],
    child: ["Dječja sjedalica", "Za djecu 15–36 kg (oko 4–12 godina)."],
    ski: ["Torba za skije", "Siguran prijevoz opreme (najviše 4 po vozilu)."],
    free: "Besplatno", flight: "Broj leta", nameboard: "Pločica s imenom (neobavezno)", luggage: "Prtljaga",
    notes: "Poruka vozaču (neobavezno)", accept: "Prihvaćam uvjete rezervacije.", back: "Natrag",
    continueWa: "Zatražite rezervaciju putem WhatsAppa", continueMail: "…ili zatražite e-poštom",
    confirmNote: "Potvrdu obično dobivate unutar 15 minuta.", total: "Ukupno",
    notFound: "Ruta nije pronađena.", allRoutes: "Sve rute",
  },
  kontakt: {
    title: "Kontakt", formTitle: "Pošaljite poruku",
    name: "Vaše ime", email: "E-pošta", phone: "Telefon", message: "Poruka",
    send: "Pošalji", orMail: "…ili nam pišite izravno e-poštom", infoTitle: "Kontaktirajte nas",
    lblPhone: "Telefon", lblEmail: "E-pošta", lblWa: "WhatsApp", lblAddress: "Adresa",
    lblHours: "Radno vrijeme", always: "Dostupni 24 sata dnevno",
  },
  footer: {
    popular: "Popularne rute", aboutLink: "O nama", information: "Informacije",
    about: "VIP Mercedes transferi u Zürichu. Fiksne cijene, obučeni vozači i praćenje letova – 24 sata dnevno.",
    follow: "Pratite nas", explore: "Istražite", company: "Tvrtka", support: "Podrška",
    callUs: "Nazovite nas", writeUs: "Pišite nam", address: "Adresa",
    about2: "O nama", faq: "Česta pitanja", rights: "Sva prava pridržana.", watermark: "Zürich",
  },
};

const tx: DictX = {
  nav: { destinations: "Destinacije", prices: "Cijene", events: "Događanja" },
  heroBadges: ["Besplatno otkazivanje", "Podrška 24/7", "Praćenje letova", "Meet & Greet"],
  heroRating: { score: "Izvrsno · 4.8/5", sub: "Izbor putnika u zračnoj luci Zürich" },
  howSec: {
    eyebrow: "Kako funkcionira", title: "Rezervirajte u tri jednostavna koraka",
    steps: [
      ["Unesite rutu i odaberite vozilo", "Navedite preuzimanje, odredište i vrijeme – zatim odaberite odgovarajuće vozilo."],
      ["Dovršite rezervaciju", "Dodajte kontakt-podatke i primite potvrdu sa svim detaljima."],
      ["Susretnite svog vozača", "Vozač vas čeka s pločicom s vašim imenom – čekanje je uključeno."],
    ],
    cta: "Saznajte cijenu",
  },
  faqSec: { eyebrow: "FAQ", title: "Česta pitanja", sub: "Sve što trebate znati o rezervaciji, na jednom mjestu.", all: "Sva pitanja" },
  hourly: {
    tabTransfer: "Transfer", tabHourly: "Po satu", duration: "Trajanje", hoursShort: "sati",
    note: "Vozač i vozilo na raspolaganju – idealno za sastanke, događanja i razgled grada.",
    cta: "Pogledajte cijene", bookingLabel: "Najam po satu",
    bookingNote: (h: string) => `Rezervacija po satu: ${h} sati – vozač na raspolaganju`,
  },
  stops: { add: "Dodaj stajanje", ph: "Usputna stanica – adresa", remove: "Ukloni", label: "Usputne stanice:" },
  done: { title: "Zahtjev poslan!", body: (r: string) => `Vaš zahtjev za transfer ${r} je izrađen i otvoren u WhatsAppu ili e-pošti. Pošaljite poruku – obično potvrđujemo unutar 15 minuta.`, hint: "Hvala na zahtjevu! Provjerite i pristiglu poštu ili mapu neželjene pošte.", payment: "Način plaćanja", home: "Natrag na početnu" },
  dest: {
    crumb: "Destinacije",
    pageTitle: "Transferi po cijeloj Švicarskoj",
    pageSub: "Iz zračne luke Zürich do svakog grada i planinskog sela. Odaberite destinaciju ili rezervirajte izravno.",
    popular: "Popularna mjesta", searchPh: "Pretražite mjesto …",
    fixed: "od CHF", onRequest: "Cijena na upit",
    hero: (n: string) => `Transfer iz zračne luke ${n}`,
    heroSub: (n: string) => `Privatni vozač i transfer iz zračne luke do i od ${n}. Fiksna cijena po vozilu, obučeni vozači i praćenje letova – 24 sata dnevno.`,
    chips: ["Fiksna cijena", "Praćenje letova", "24/7", "Licencirani vozači"],
    calc: "Izračunaj cijenu",
    f1: ["Fiksne cijene", "Cijena je poznata prije vožnje – bez iznenađenja."],
    f2: ["Uvijek na vrijeme", "Pratimo vaš let i prilagođavamo vrijeme preuzimanja."],
    f3: ["Sigurno i licencirano", "Obučeni vozači, njegovana Mercedes vozila."],
    vehiclesFor: (n: string) => `Vozila za ${n}`,
    routeKnown: (n: string, p: string) => `Fiksna cijena zračna luka Zürich → ${n}: od CHF ${p} po vozilu.`,
    routeDetail: "Pogledajte rutu detaljno",
    seo: (n: string, r: string) => [
      [`Taksi iz zračne luke ${n} po fiksnoj cijeni`, `Tražite pouzdan transfer za ${n}? Kod nas rezervirate privatni transfer do i od zračne luke Zürich (ZRH) po zajamčenoj fiksnoj cijeni po vozilu. Bez taksimetra, bez skrivenih doplata: cijena je poznata već pri rezervaciji, bez obzira na promet ili doba dana.`],
      [`Iz zračne luke Zürich (ZRH) do ${n}`, `Vozač vas čeka s pločicom s vašim imenom izravno u dolaznoj dvorani (Meet & Greet) i pomaže s prtljagom. Za povratak iz regije ${r} uračunavamo promet i vrijeme za prijavu, kako biste u zračnu luku stigli opušteno i na vrijeme.`],
      [`24/7 uz praćenje letova`, `Pratimo vaš let u stvarnom vremenu. Ako zrakoplov sleti ranije ili kasnije, vrijeme preuzimanja automatski se prilagođava – čekanje nakon slijetanja uključeno je u fiksnu cijenu. Radimo 365 dana u godini.`],
      [`Pravo vozilo za svaku prigodu`, `Poslovni put, obiteljski odmor ili skijanje: od Business klase do prostranog kombija s do 7 mjesta, pronaći ćete odgovarajuće vozilo za transfer do ${n}. Dječje sjedalice i nosiljke su besplatne.`],
    ],
    faqTitle: (n: string) => `Česta pitanja o transferu za ${n}`,
    faq: (n: string) => [
      [`Koliko košta taksi iz zračne luke za ${n}?`, `Cijena je fiksna po vozilu i ovisi o udaljenosti od zračne luke Zürich te klasi vozila. Zatražite ponudu u nekoliko sekundi – fiksnu cijenu dobivate prije vožnje.`],
      [`Kako rezervirati transfer za ${n}?`, `Unesite adresu, odaberite datum i vrijeme, dodajte broj leta – gotovo. Rezervacija traje manje od minute, online ili putem WhatsAppa.`],
      ["Je li praćenje letova uključeno?", "Da. Pratimo svaki let i automatski prilagođavamo vrijeme preuzimanja. Čekanje nakon slijetanja uključeno je u cijenu."],
      ["Mogu li besplatno otkazati?", "Da, otkazivanje je besplatno do 24 sata prije planiranog preuzimanja."],
    ],
    more: "Ostale destinacije", all: "Sva mjesta",
    ctaTitle: "Spremni stići opušteno?",
    ctaSub: "Primite fiksnu, transparentnu cijenu u nekoliko sekundi – bez računa.",
    ctaBtn: "Rezerviraj odmah",
  },
  prices: {
    crumb: "Cijene", title: "Transparentne fiksne cijene",
    sub: "Svaka vožnja po fiksnoj cijeni po vozilu – uklj. 60 min. čekanja u zračnoj luci, Meet & Greet i praćenje letova. Bez skrivenih troškova.",
    f1: ["Zajamčena fiksna cijena", "Cijena se fiksira pri rezervaciji."],
    f2: ["Praćenje letova", "Besplatno čekanje u slučaju kašnjenja."],
    f3: ["Sve uključeno", "Porezi, cestarine i Meet & Greet uključeni."],
    classesTitle: "Naše klase vozila i cijene",
    from: "od", perVehicle: "po vozilu", book: "Rezerviraj",
    tableTitle: "Fiksne cijene po rutama",
    tableSub: "Sve rute iz zračne luke Zürich (ZRH) – cijena po vozilu, ne po osobi.",
    colDest: "Odredište", colKm: "Udaljenost", colDur: "Trajanje",
    destTitle: "Cijene po destinacijama",
    destSub: "Više od 250 mjesta u Švicarskoj i susjednim regijama. Odaberite destinaciju za detalje.",
    request: "Na upit",
  },
  events: {
    crumb: "Događanja", title: "Događanja u Švicarskoj – vaš privatni transfer",
    sub: "Rezervirajte vozača za najpoznatije sajmove, festivale i panoramska putovanja Švicarske.",
    all: "Sva", book: "Rezerviraj transfer",
  },
};

export const hr = { t, tx };
