import type { Dict } from "../i18n";
import type { DictX } from "../i18nX";
import { REVIEWS } from "./shared";

const t: Dict = {
  meta: { title: "AirportTransfers Zurigo | Transfer aeroporto ZRH · Mercedes VIP", desc: "Transfer privati dall'aeroporto di Zurigo a prezzo fisso. Autisti qualificati, monitoraggio voli, 24/7." },
  topbar: "Zurigo · Transfer privati",
  nav: { routes: "Tratte", fleet: "Veicoli", gallery: "Galleria", contact: "Contatto", book: "Prenota ora", home: "Home" },
  hero: {
    eyebrow: "Zurigo · Mercedes VIP", title1: "Transfer da Zurigo", title2: "in Mercedes VIP",
    sub: "Prezzo fisso · Autisti qualificati · Monitoraggio voli · Assistenza 24/7",
    pills: ["Prezzo fisso", "Assistenza 24/7", "Conferma immediata"],
    cta1: "Prenota ora", cta2: "Tratte più richieste",
  },
  form: {
    title: "Richiedi un transfer",
    from: "Luogo di partenza", fromPh: "es. Aeroporto di Zurigo, Basilea …",
    to: "Destinazione", toPh: "es. Zermatt, St. Moritz …",
    date: "Data", time: "Ora", pax: "Passeggeri", kids: "Bambini",
    wa: "Richiedi via WhatsApp", callNow: "Chiama ora", callSub: "Disponibili 24 ore su 24", mail: "Richiedi via e-mail",
    search: "Cerca", note: "Seggiolini gratuiti · Nessun costo extra",
  },
  msg: {
    title: "Richiesta di prenotazione – Transfer aeroporto Zurigo", contactTitle: "Richiesta di contatto – Sito web",
    from: "Partenza", to: "Destinazione", date: "Data", time: "Ora", pax: "Passeggeri", kids: "Bambini",
    name: "Nome", email: "E-mail", phone: "Telefono", message: "Messaggio",
    subject: "Richiesta – AirportTransfers Zurigo",
  },
  routesSec: {
    eyebrow: "Tratte", title: "Tratte più richieste",
    sub: "Le nostre tratte di transfer aeroportuale più prenotate – a prezzo fisso garantito.",
    pageTitle: "Tratte",
    pageSub: "Tutte le tratte dall'aeroporto di Zurigo (ZRH) – prezzo fisso per veicolo, incl. 60 min. di attesa.",
    from: "da", origin: "Aeroporto di Zurigo (ZRH)",
    all: "Vedi tutte", allNote: "Un'altra destinazione? Copriamo tutta la Svizzera – contattateci.",
  },
  fleetSec: {
    eyebrow: "Veicoli", title: "La nostra flotta",
    sub: "Veicoli VIP curati e confortevoli per ogni gruppo.",
    pageTitle: "Veicoli",
    pageSub: "Tutti i veicoli con autista professionista, WiFi e acqua minerale a bordo.",
    pax: "Passeggeri", bags: "Bagagli", cta: "Richiedi ora",
    features: ["WiFi gratuito", "Acqua minerale", "Seggiolini su richiesta", "Monitoraggio voli"],
  },
  gallerySec: { eyebrow: "Galleria", title: "Galleria", pageTitle: "Galleria", pageSub: "Immagini dei nostri veicoli e dei nostri viaggi.", all: "Vedi tutto" },
  reviewsSec: { eyebrow: "Recensioni", title: "Cosa dicono i nostri ospiti", sub: "Esperienze vere di veri viaggiatori.", count: "recensioni", list: REVIEWS },
  blogSec: {
    title: "Blog", pageSub: "Consigli di viaggio, guide alle tratte e informazioni utili sui transfer dall'aeroporto di Zurigo.",
    read: "Leggi di più", minRead: "min di lettura", more: "Altri articoli", back: "Tutti gli articoli", published: "Pubblicato il",
  },
  faqPage: {
    title: "Domande frequenti", sub: "Risposte alle domande più importanti su prenotazione, prezzi e procedura.",
    list: [
      ["Come prenoto un transfer?", "Nel modo più rapido tramite l'assistente di prenotazione su questo sito o direttamente via WhatsApp. La conferma arriva di norma entro 15 minuti."],
      ["I prezzi sono davvero fissi?", "Sì. Il prezzo indicato alla prenotazione vale per veicolo e non cambia – indipendentemente da traffico, meteo od orario. Nessun supplemento notturno o per bagagli."],
      ["Cosa succede se il volo è in ritardo?", "Monitoriamo il vostro volo in tempo reale e adattiamo automaticamente l'orario di prelievo. L'attesa dopo l'atterraggio è gratuita."],
      ["Dove incontro l'autista in aeroporto?", "Il vostro autista vi attende con un cartello con il nome direttamente nella hall degli arrivi (Meet & Greet) e vi accompagna al veicolo."],
      ["Come posso pagare?", "Comodamente in auto: contanti, carta di credito o TWINT. I clienti aziendali possono ricevere una fattura cumulativa su richiesta."],
      ["Posso annullare gratuitamente?", "Sì, fino a 24 ore prima del prelievo previsto l'annullamento è gratuito con rimborso completo."],
      ["Sono disponibili seggiolini per bambini?", "Sì, ovetti e seggiolini sono gratuiti. Basta indicare numero ed età dei bambini al momento della prenotazione."],
      ["Trasportate sci e bagagli speciali?", "Le sacche da sci viaggiano gratis (max. 4 per veicolo). I bagagli ingombranti come sacche da golf o passeggini vanno segnalati alla prenotazione."],
    ],
  },
  booking: { title: "Prenotazione", steps: ["Tratta e orario", "Veicolo", "Contatto e pagamento"], route: "Tratta", choose: "Selezionare la destinazione …", next: "Avanti" },
  detail: {
    selectCar: "Scegliete il vostro veicolo", summary: "Riepilogo del viaggio",
    pickupLoc: "Luogo di partenza", dropoffLoc: "Destinazione", distance: "Distanza totale", time: "Tempo totale",
    vehicle: "Veicolo selezionato", priceNote: "Tutti i prezzi includono IVA e tasse.", select: "Seleziona",
    feats: ["Meet & Greet incluso", "Cancellazione gratuita", "Attesa gratuita", "Viaggio sicuro e affidabile"],
    noticeTitle: "Avviso importante", noticeText: "Le prenotazioni effettuate meno di 2 ore prima del prelievo potrebbero non essere garantite nelle ore di punta. Vi preghiamo di prenotare per tempo.",
    payTitle: "Scegliete il metodo di pagamento",
    payOptions: [["TWINT", "Pagamento con TWINT in auto"], ["Contanti", "Pagamento in contanti in auto"], ["Carta di credito", "Pagamento con carta in auto"]],
    paxTitle: "Dati dei passeggeri", name: "Nome", surname: "Cognome", email: "E-mail", phone: "Telefono",
    baby: ["Ovetto", "Per neonati 0–13 kg (ca. 0–4 anni)."],
    child: ["Seggiolino", "Per bambini 15–36 kg (ca. 4–12 anni)."],
    ski: ["Sacca da sci", "Trasporto sicuro dell'attrezzatura (max. 4 per veicolo)."],
    free: "Gratis", flight: "Numero del volo", nameboard: "Cartello con nome (opzionale)", luggage: "Bagagli",
    notes: "Messaggio all'autista (opzionale)", accept: "Accetto le condizioni di prenotazione.", back: "Indietro",
    continueWa: "Richiedi la prenotazione via WhatsApp", continueMail: "…o richiedi via e-mail",
    confirmNote: "Riceverete la conferma di norma entro 15 minuti.", total: "Totale",
    notFound: "Tratta non trovata.", allRoutes: "Tutte le tratte",
  },
  kontakt: {
    title: "Contatto", formTitle: "Inviate un messaggio",
    name: "Il vostro nome", email: "E-mail", phone: "Telefono", message: "Messaggio",
    send: "Invia", orMail: "…o scrivete direttamente via e-mail", infoTitle: "Contattateci",
    lblPhone: "Telefono", lblEmail: "E-mail", lblWa: "WhatsApp", lblAddress: "Indirizzo",
    lblHours: "Orari d'ufficio", always: "Disponibili 24 ore su 24",
  },
  footer: {
    popular: "Tratte più richieste", aboutLink: "Chi siamo", information: "Informazioni",
    about: "Transfer VIP in Mercedes a Zurigo. Prezzi fissi, autisti qualificati e monitoraggio voli – 24 ore su 24.",
    follow: "Seguiteci", explore: "Esplora", company: "Azienda", support: "Assistenza",
    callUs: "Chiamateci", writeUs: "Scriveteci", address: "Indirizzo",
    about2: "Chi siamo", faq: "Domande frequenti", rights: "Tutti i diritti riservati.", watermark: "Zurigo",
  },
};

const tx: DictX = {
  nav: { destinations: "Destinazioni", prices: "Prezzi", events: "Eventi" },
  heroBadges: ["Cancellazione gratuita", "Assistenza 24/7", "Monitoraggio voli", "Meet & Greet"],
  heroRating: { score: "Eccellente · 4.8/5", sub: "Scelto dai viaggiatori all'aeroporto di Zurigo" },
  howSec: {
    eyebrow: "Come funziona", title: "Prenotate in tre semplici passi",
    steps: [
      ["Inserite la tratta e scegliete il veicolo", "Indicate partenza, destinazione e orario – poi scegliete il veicolo adatto."],
      ["Completate la prenotazione", "Aggiungete i vostri dati e ricevete la conferma con tutti i dettagli."],
      ["Incontrate il vostro autista", "Il vostro autista vi attende con un cartello con il nome – attesa inclusa."],
    ],
    cta: "Richiedi il prezzo",
  },
  faqSec: { eyebrow: "FAQ", title: "Domande frequenti", sub: "Tutto quello che serve sapere sulla vostra prenotazione, a colpo d'occhio.", all: "Vedi tutte le domande" },
  hourly: {
    tabTransfer: "Transfer", tabHourly: "A ore", duration: "Durata", hoursShort: "ore",
    note: "Autista e veicolo a vostra disposizione – ideale per appuntamenti, eventi e tour in città.",
    cta: "Vedi i prezzi", bookingLabel: "Noleggio a ore",
    bookingNote: (h: string) => `Prenotazione a ore: ${h} ore – autista a disposizione`,
  },
  dest: {
    crumb: "Destinazioni",
    pageTitle: "Transfer in tutta la Svizzera",
    pageSub: "Dall'aeroporto di Zurigo a ogni città e villaggio di montagna. Scegliete la destinazione o prenotate direttamente.",
    popular: "Località più richieste", searchPh: "Cerca una località …",
    fixed: "da CHF", onRequest: "Prezzo su richiesta",
    hero: (n: string) => `Transfer aeroportuale ${n}`,
    heroSub: (n: string) => `Servizio autista privato e transfer aeroportuale da e per ${n}. Prezzo fisso per veicolo, autisti qualificati e monitoraggio voli – 24 ore su 24.`,
    chips: ["Prezzo fisso", "Monitoraggio voli", "24/7", "Autisti autorizzati"],
    calc: "Calcola il prezzo",
    f1: ["Prezzi fissi", "Il prezzo è definito prima del viaggio – senza sorprese."],
    f2: ["Sempre puntuali", "Monitoriamo il vostro volo e adattiamo l'orario di prelievo."],
    f3: ["Sicuri e autorizzati", "Autisti qualificati, Mercedes sempre in perfette condizioni."],
    vehiclesFor: (n: string) => `Veicoli per ${n}`,
    routeKnown: (n: string, p: string) => `Prezzo fisso aeroporto di Zurigo → ${n}: da CHF ${p} per veicolo.`,
    routeDetail: "Vedi la tratta in dettaglio",
    seo: (n: string, r: string) => [
      [`Taxi aeroportuale ${n} a prezzo fisso`, `Cercate un transfer aeroportuale affidabile per ${n}? Con noi prenotate il vostro transfer privato da e per l'aeroporto di Zurigo (ZRH) a un prezzo fisso garantito per veicolo. Nessun tassametro, nessun supplemento nascosto: il prezzo è definito già alla prenotazione, indipendentemente dal traffico o dall'orario.`],
      [`Dall'aeroporto di Zurigo (ZRH) a ${n}`, `Il vostro autista vi attende con un cartello con il nome direttamente nella hall degli arrivi (Meet & Greet) e vi aiuta con i bagagli. Per il ritorno da ${r} calcoliamo traffico e tempi di check-in, così arrivate in aeroporto rilassati e puntuali.`],
      [`24/7 con monitoraggio dei voli`, `Monitoriamo il vostro volo in tempo reale. Se l'aereo atterra prima o dopo, l'orario di prelievo si adatta automaticamente – l'attesa dopo l'atterraggio è inclusa nel prezzo fisso. Il servizio è attivo 365 giorni all'anno.`],
      [`Il veicolo giusto per ogni occasione`, `Viaggio d'affari, vacanza in famiglia o settimana bianca: dalla Business Class al van spazioso fino a 7 posti, trovate il veicolo adatto al vostro transfer per ${n}. Seggiolini e ovetti sono gratuiti.`],
    ],
    faqTitle: (n: string) => `Domande frequenti sul transfer per ${n}`,
    faq: (n: string) => [
      [`Quanto costa un taxi aeroportuale per ${n}?`, `Il prezzo è fisso per veicolo e dipende dalla distanza dall'aeroporto di Zurigo e dalla classe del veicolo. Richiedete un preventivo in pochi secondi – riceverete il prezzo fisso prima del viaggio.`],
      [`Come prenoto il mio transfer per ${n}?`, `Inserite l'indirizzo, scegliete data e ora, aggiungete il numero del volo – fatto. La prenotazione richiede meno di un minuto, online o via WhatsApp.`],
      ["Il monitoraggio dei voli è incluso?", "Sì. Monitoriamo ogni volo e adattiamo automaticamente l'orario di prelievo. L'attesa dopo l'atterraggio è inclusa nel prezzo."],
      ["Posso annullare gratuitamente?", "Sì, l'annullamento è gratuito fino a 24 ore prima del prelievo previsto."],
    ],
    more: "Altre destinazioni", all: "Tutte le località",
    ctaTitle: "Pronti ad arrivare rilassati?",
    ctaSub: "Ricevete in pochi secondi un prezzo fisso e trasparente – senza bisogno di un account.",
    ctaBtn: "Prenota ora",
  },
  prices: {
    crumb: "Prezzi", title: "Prezzi fissi e trasparenti",
    sub: "Ogni viaggio a prezzo fisso per veicolo – incl. 60 min. di attesa in aeroporto, Meet & Greet e monitoraggio voli. Nessun costo nascosto.",
    f1: ["Prezzo fisso garantito", "Il prezzo viene bloccato alla prenotazione."],
    f2: ["Monitoraggio voli", "Attesa gratuita in caso di ritardo."],
    f3: ["Tutto incluso", "Tasse, pedaggi e Meet & Greet compresi."],
    classesTitle: "Le nostre classi di veicoli e i prezzi",
    from: "da", perVehicle: "per veicolo", book: "Prenota",
    tableTitle: "Prezzi fissi per tratta",
    tableSub: "Tutte le tratte dall'aeroporto di Zurigo (ZRH) – prezzo per veicolo, non per persona.",
    colDest: "Destinazione", colKm: "Distanza", colDur: "Durata",
    destTitle: "Prezzi per destinazione",
    destSub: "Oltre 250 località in Svizzera e nelle regioni vicine. Scegliete la vostra destinazione per i dettagli.",
    request: "Su richiesta",
  },
  events: {
    crumb: "Eventi", title: "Eventi in Svizzera – il vostro transfer privato",
    sub: "Riservate il vostro autista per le fiere, i festival e i viaggi panoramici più celebri della Svizzera.",
    all: "Tutti", book: "Prenota il transfer",
  },
};

export const it = { t, tx };
