import type { Dict } from "../i18n";
import type { DictX } from "../i18nX";

const t: Dict = {
  meta: { title: "Zuerich Airport Taxi - Táxi Aeroporto de Zurique & Serviço de Chauffeur Suíça", desc: "Transfers premium do aeroporto de Zurique (ZRH) para toda a Suíça – preços fixos, motoristas profissionais e monitorização de voos. Reserve o seu transfer em 1 minuto!" },
  topbar: "Zurique · Transfers privados",
  nav: { routes: "Rotas", fleet: "Veículos", gallery: "Galeria", contact: "Contacto", book: "Reservar", home: "Início" },
  hero: {
    eyebrow: "Zurique · Mercedes VIP", title1: "Transfers em Zurique", title2: "em Mercedes VIP",
    sub: "Preço fixo · Motoristas qualificados · Monitorização de voos · Assistência 24/7",
    pills: ["Preço fixo", "Assistência 24/7", "Confirmação imediata"],
    cta1: "Reservar", cta2: "Rotas populares",
  },
  form: {
    title: "Pedir um transfer",
    from: "Local de recolha", fromPh: "p. ex. Aeroporto de Zurique, Basileia …",
    to: "Destino", toPh: "p. ex. Zermatt, St. Moritz …",
    date: "Data", time: "Hora", pax: "Passageiros", kids: "Crianças",
    wa: "Pedir via WhatsApp", callNow: "Ligar agora", callSub: "Disponíveis 24 horas por dia", mail: "Pedir por e-mail",
    search: "Procurar", note: "Cadeiras de criança grátis · Sem custos extra",
  },
  msg: {
    title: "Pedido de reserva – Transfer aeroporto de Zurique", contactTitle: "Pedido de contacto – Site",
    from: "Recolha", to: "Destino", date: "Data", time: "Hora", pax: "Passageiros", kids: "Crianças",
    name: "Nome", email: "E-mail", phone: "Telefone", message: "Mensagem",
    subject: "Pedido – AirportTransfers Zurique",
  },
  routesSec: {
    eyebrow: "Rotas", title: "Rotas populares",
    sub: "As nossas rotas de transfer mais reservadas – a preço fixo garantido.",
    pageTitle: "Rotas",
    pageSub: "Todas as rotas a partir do aeroporto de Zurique (ZRH) – preço fixo por veículo, incl. 60 min. de espera.",
    from: "desde", origin: "Aeroporto de Zurique (ZRH)",
    all: "Ver todas", allNote: "Outro destino? Cobrimos toda a Suíça – fale connosco.",
  },
  fleetSec: {
    eyebrow: "Veículos", title: "A nossa frota",
    sub: "Veículos VIP cuidados e confortáveis para todos os grupos.",
    pageTitle: "Veículos",
    pageSub: "Todos os veículos com motorista profissional, WiFi e água mineral a bordo.",
    pax: "Passageiros", bags: "Bagagem", cta: "Pedir agora",
    features: ["WiFi grátis", "Água mineral", "Cadeiras de criança a pedido", "Monitorização de voos"],
  },
  gallerySec: { eyebrow: "Galeria", title: "Galeria", pageTitle: "Galeria", pageSub: "Imagens dos nossos veículos e das nossas viagens.", all: "Ver tudo" },
  reviewsSec: { eyebrow: "Avaliações", title: "O que dizem os nossos clientes", sub: "Experiências reais de verdadeiros viajantes.", count: "avaliações", list: [
      { text: "Motorista pontual, carro impecável e preço fixo sem surpresas. Recomendo!", name: "João M.", route: "ZRH → Zermatt", flag: "🇵🇹" },
      { text: "Reserva pelo WhatsApp em menos de um minuto. Confirmação imediata.", name: "Ana C.", route: "ZRH → Luzern", flag: "🇧🇷" },
      { text: "O voo atrasou e o motorista esperou sem custo extra. Serviço de confiança.", name: "Pedro S.", route: "ZRH → Interlaken", flag: "🇵🇹" },
      { text: "Cadeirinha para o bebé já instalada. Viagem tranquila até Grindelwald.", name: "Mariana L.", route: "ZRH → Grindelwald", flag: "🇧🇷" },
      { text: "Mercedes confortável, WiFi e água a bordo. Experiência verdadeiramente premium.", name: "Rui F.", route: "ZRH → Genève", flag: "🇵🇹" },
    ] },
  blogSec: {
    title: "Blog", pageSub: "Dicas de viagem, guias de rotas e informações úteis sobre transfers do aeroporto de Zurique.",
    read: "Ler mais", minRead: "min de leitura", more: "Mais artigos", back: "Todos os artigos", published: "Publicado em",
  },
  faqPage: {
    title: "Perguntas frequentes", sub: "Respostas às perguntas essenciais sobre reserva, preços e funcionamento.",
    list: [
      ["Como reservo um transfer?", "O mais rápido é o assistente de reservas neste site ou diretamente via WhatsApp. Normalmente recebe a confirmação em 15 minutos."],
      ["Os preços são mesmo fixos?", "Sim. O preço indicado na reserva aplica-se por veículo e não muda – independentemente do trânsito, do tempo ou da hora. Não há suplementos noturnos nem por bagagem."],
      ["O que acontece se o meu voo atrasar?", "Monitorizamos o seu voo em tempo real e ajustamos automaticamente a hora de recolha. A espera após a aterragem é gratuita."],
      ["Onde encontro o meu motorista no aeroporto?", "O seu motorista espera-o com uma placa com o seu nome na sala de chegadas (Meet & Greet) e acompanha-o até ao veículo."],
      ["Como posso pagar?", "Comodamente no veículo: dinheiro, cartão de crédito ou TWINT. Clientes empresariais podem receber fatura agrupada a pedido."],
      ["Posso cancelar gratuitamente?", "Sim, até 24 horas antes da recolha prevista o cancelamento é gratuito com reembolso total."],
      ["Há cadeiras de criança disponíveis?", "Sim, ovinhos e cadeiras de criança são gratuitos. Basta indicar o número e a idade das crianças na reserva."],
      ["Transportam esquis e bagagem especial?", "Os sacos de esqui viajam grátis (máx. 4 por veículo). Bagagem volumosa, como sacos de golfe ou carrinhos de bebé, deve ser indicada na reserva."],
    ],
  },
  booking: { title: "Reserva", steps: ["Rota e hora", "Veículo", "Contacto e pagamento"], route: "Rota", choose: "Escolha o destino …", next: "Continuar" },
  detail: {
    selectCar: "Escolha o seu veículo", summary: "Resumo da viagem",
    pickupLoc: "Local de recolha", dropoffLoc: "Destino", distance: "Distância total", time: "Tempo total",
    vehicle: "Veículo selecionado", priceNote: "Todos os preços incluem IVA e taxas.", select: "Selecionar",
    feats: ["Meet & Greet incluído", "Cancelamento gratuito", "Espera gratuita", "Viagem segura e fiável"],
    noticeTitle: "Aviso importante", noticeText: "Reservas feitas menos de 2 horas antes da recolha podem não ser garantidas em horas de ponta. Reserve com antecedência.",
    payTitle: "Escolha o método de pagamento",
    payOptions: [["TWINT", "Pagamento com TWINT no veículo"], ["Dinheiro", "Pagamento em dinheiro no veículo"], ["Cartão de crédito", "Pagamento com cartão no veículo"]],
    paxTitle: "Dados dos passageiros", name: "Nome", surname: "Apelido", email: "E-mail", phone: "Telefone",
    baby: ["Ovinho", "Para bebés de 0–13 kg (aprox. 0–4 anos)."],
    child: ["Cadeira de criança", "Para crianças de 15–36 kg (aprox. 4–12 anos)."],
    ski: ["Saco de esqui", "Transporte seguro do equipamento (máx. 4 por veículo)."],
    free: "Grátis", flight: "Número do voo", nameboard: "Placa com nome (opcional)", luggage: "Bagagem",
    notes: "Mensagem ao motorista (opcional)", accept: "Aceito as condições de reserva.", back: "Voltar",
    continueWa: "Pedir a reserva via WhatsApp", continueMail: "…ou pedir por e-mail",
    confirmNote: "Normalmente recebe a confirmação em 15 minutos.", total: "Total",
    notFound: "Rota não encontrada.", allRoutes: "Todas as rotas",
  },
  kontakt: {
    title: "Contacto", formTitle: "Enviar uma mensagem",
    name: "O seu nome", email: "E-mail", phone: "Telefone", message: "Mensagem",
    send: "Enviar", orMail: "…ou escreva diretamente por e-mail", infoTitle: "Fale connosco",
    lblPhone: "Telefone", lblEmail: "E-mail", lblWa: "WhatsApp", lblAddress: "Morada",
    lblHours: "Horário de expediente", always: "Disponíveis 24 horas por dia",
  },
  footer: {
    popular: "Rotas populares", aboutLink: "Sobre nós", information: "Informações",
    about: "Transfers VIP em Mercedes em Zurique. Preços fixos, motoristas qualificados e monitorização de voos – 24/7.",
    follow: "Siga-nos", explore: "Explorar", company: "Empresa", support: "Assistência",
    callUs: "Ligue-nos", writeUs: "Escreva-nos", address: "Morada",
    about2: "Sobre nós", faq: "Perguntas frequentes", rights: "Todos os direitos reservados.", watermark: "Zurique",
  },
};

const tx: DictX = {
  nav: { destinations: "Destinos", prices: "Preços", events: "Eventos" },
  heroBadges: ["Cancelamento gratuito", "Assistência 24/7", "Monitorização de voos", "Preço fixo"],
  heroRating: { score: "Excelente · 4.8/5", sub: "A escolha dos viajantes no aeroporto de Zurique" },
  howSec: {
    eyebrow: "Como funciona", title: "Reserve em três passos simples",
    steps: [
      ["Introduza a rota e escolha o veículo", "Indique recolha, destino e hora – depois escolha o veículo adequado."],
      ["Conclua a sua reserva", "Adicione os seus dados e receba a confirmação com todos os detalhes."],
      ["Encontre o seu motorista", "O seu motorista espera-o com uma placa com o seu nome – a espera está incluída."],
    ],
    cta: "Obter preço",
  },
  faqSec: { eyebrow: "FAQ", title: "Perguntas frequentes", sub: "Tudo o que precisa de saber sobre a sua reserva, num relance.", all: "Ver todas as perguntas" },
  hourly: {
    tabTransfer: "Transfer", tabHourly: "Por hora", duration: "Duração", hoursShort: "horas",
    note: "Motorista e veículo à sua disposição – ideal para reuniões, eventos e passeios pela cidade.",
    cta: "Ver preços", bookingLabel: "Aluguer por hora",
    bookingNote: (h: string) => `Reserva por hora: ${h} horas – motorista à disposição`,
  },
  stops: { add: "Adicionar paragem", ph: "Paragem – morada", remove: "Remover", label: "Paragens intermédias:" },
  busy: { title: "Os nossos veículos estão ocupados nesta hora", text: "Já existe um transfer agendado neste intervalo. Escolha outra hora ou contacte-nos – encontraremos uma solução.", cta: "Falar com o apoio ao cliente", next: "Próxima hora livre:" },
  night: { title: "Reserva noturna de última hora não é possível", text: "Durante a noite não aceitamos automaticamente viagens com menos de 2 horas de antecedência. Escolha uma hora mais tarde ou contacte-nos diretamente – verificaremos a disponibilidade pessoalmente.", earliest: "O mais cedo a partir das:" },
  done: { title: "Pedido enviado!", body: (r: string) => `O seu pedido de transfer ${r} foi criado e aberto no WhatsApp ou por e-mail. Envie a mensagem – normalmente confirmamos em 15 minutos.`, hint: "Obrigado pelo seu pedido! Verifique também a caixa de entrada ou a pasta de spam.", payment: "Método de pagamento", home: "Voltar ao início" },
  dest: {
    crumb: "Destinos",
    pageTitle: "Transfers em toda a Suíça",
    pageSub: "Do aeroporto de Zurique a todas as cidades e aldeias de montanha. Escolha o seu destino ou reserve diretamente.",
    popular: "Locais populares", searchPh: "Procurar um local …",
    fixed: "desde CHF", onRequest: "Preço sob consulta",
    hero: (n: string) => `Transfer de aeroporto ${n}`,
    heroSub: (n: string) => `Serviço de motorista privado e transfer de aeroporto de e para ${n}. Preço fixo por veículo, motoristas qualificados e monitorização de voos – 24 horas por dia.`,
    chips: ["Preço fixo", "Monitorização de voos", "24/7", "Motoristas licenciados"],
    calc: "Calcular preço",
    f1: ["Preços fixos", "O preço é definido antes da viagem – sem surpresas."],
    f2: ["Sempre pontuais", "Monitorizamos o seu voo e ajustamos a hora de recolha."],
    f3: ["Seguro e licenciado", "Motoristas qualificados, Mercedes sempre impecáveis."],
    vehiclesFor: (n: string) => `Veículos para ${n}`,
    routeKnown: (n: string, p: string) => `Preço fixo aeroporto de Zurique → ${n}: desde CHF ${p} por veículo.`,
    routeDetail: "Ver a rota em detalhe",
    seo: (n: string, r: string) => [
      [`Táxi de aeroporto ${n} a preço fixo`, `Procura um transfer de aeroporto fiável para ${n}? Connosco reserva o seu transfer privado de e para o aeroporto de Zurique (ZRH) a um preço fixo garantido por veículo. Sem taxímetro, sem suplementos escondidos: o preço fica definido logo na reserva, independentemente do trânsito ou da hora.`],
      [`Do aeroporto de Zurique (ZRH) para ${n}`, `O seu motorista espera-o com uma placa com o seu nome na sala de chegadas (Meet & Greet) e ajuda com a bagagem. Para o regresso de ${r}, calculamos o trânsito e os tempos de check-in para que chegue ao aeroporto descansado e a horas.`],
      [`24/7 com monitorização de voos`, `Monitorizamos o seu voo em tempo real. Se o avião aterrar mais cedo ou mais tarde, a hora de recolha ajusta-se automaticamente – a espera após a aterragem está incluída no preço fixo. Operamos 365 dias por ano.`],
      [`O veículo certo para cada ocasião`, `Viagem de negócios, férias em família ou semana de esqui: da Business Class à carrinha espaçosa até 7 lugares, encontra o veículo ideal para o seu transfer para ${n}. Cadeiras de criança e ovinhos são gratuitos.`],
    ],
    faqTitle: (n: string) => `Perguntas frequentes sobre o transfer para ${n}`,
    faq: (n: string) => [
      [`Quanto custa um táxi de aeroporto para ${n}?`, `O preço é fixo por veículo e depende da distância ao aeroporto de Zurique e da classe do veículo. Peça um orçamento em segundos – recebe o preço fixo antes da viagem.`],
      [`Como reservo o meu transfer para ${n}?`, `Introduza a morada, escolha data e hora, adicione o número do voo – pronto. A reserva demora menos de um minuto, online ou via WhatsApp.`],
      ["A monitorização de voos está incluída?", "Sim. Monitorizamos todos os voos e ajustamos automaticamente a hora de recolha. A espera após a aterragem está incluída no preço."],
      ["Posso cancelar gratuitamente?", "Sim, o cancelamento é gratuito até 24 horas antes da recolha prevista."],
    ],
    more: "Mais destinos", all: "Todos os locais",
    ctaTitle: "Pronto para chegar descansado?",
    ctaSub: "Receba em segundos um preço fixo e transparente – sem necessidade de conta.",
    ctaBtn: "Reservar",
  },
  prices: {
    crumb: "Preços", title: "Preços fixos e transparentes",
    sub: "Cada viagem a preço fixo por veículo – incl. 60 min. de espera no aeroporto, Meet & Greet e monitorização de voos. Sem custos escondidos.",
    f1: ["Preço fixo garantido", "O preço fica bloqueado na reserva."],
    f2: ["Monitorização de voos", "Espera gratuita em caso de atraso."],
    f3: ["Tudo incluído", "Impostos, portagens e Meet & Greet incluídos."],
    classesTitle: "As nossas classes de veículos e preços",
    from: "desde", perVehicle: "por veículo", book: "Reservar",
    tableTitle: "Preços fixos por rota",
    tableSub: "Todas as rotas do aeroporto de Zurique (ZRH) – preço por veículo, não por pessoa.",
    colDest: "Destino", colKm: "Distância", colDur: "Duração",
    destTitle: "Preços por destino",
    destSub: "Mais de 250 locais na Suíça e nas regiões vizinhas. Escolha o seu destino para ver os detalhes.",
    request: "Sob consulta",
  },
  events: {
    crumb: "Eventos", title: "Eventos na Suíça – o seu transfer privado",
    sub: "Reserve o seu motorista para as feiras, festivais e viagens panorâmicas mais conhecidas da Suíça.",
    all: "Todos", book: "Reservar transfer",
  },
};

export const pt = { t, tx };
