import type { Dict } from "../i18n";
import type { DictX } from "../i18nX";

const t: Dict = {
  meta: { title: "Zuerich Airport Taxi - Taksi aerodrom Cirih & šoferska služba Švajcarska", desc: "Premijum transferi sa aerodroma Cirih (ZRH) po celoj Švajcarskoj – fiksne cene, profesionalni vozači i praćenje letova. Rezervišite transfer za 1 minut!" },
  topbar: "Cirih · Privatni transferi",
  nav: { routes: "Rute", fleet: "Vozila", gallery: "Galerija", contact: "Kontakt", book: "Rezerviši odmah", home: "Početna" },
  hero: {
    eyebrow: "Cirih · VIP Mercedes", title1: "Transferi u Cirihu", title2: "u VIP Mercedesu",
    sub: "Fiksna cena · Obučeni vozači · Praćenje letova · Podrška 24/7",
    pills: ["Fiksna cena", "Podrška 24/7", "Trenutna potvrda"],
    cta1: "Rezerviši odmah", cta2: "Popularne rute",
  },
  form: {
    title: "Zatražite transfer",
    from: "Mesto preuzimanja", fromPh: "npr. aerodrom Cirih, Bazel …",
    to: "Odredište", toPh: "npr. Cermat, Sankt Moric …",
    date: "Datum", time: "Vreme", pax: "Putnici", kids: "Deca",
    wa: "Zatražite preko WhatsApp-a", callNow: "Pozovite odmah", callSub: "Dostupni 24 časa dnevno", mail: "Zatražite e-poštom",
    search: "Pretraži", note: "Besplatna dečja sedišta · Bez dodatnih troškova",
  },
  msg: {
    title: "Zahtev za rezervaciju – aerodromski transfer Cirih", contactTitle: "Zahtev za kontakt – veb-sajt",
    from: "Preuzimanje", to: "Odredište", date: "Datum", time: "Vreme", pax: "Putnici", kids: "Deca",
    name: "Ime", email: "E-pošta", phone: "Telefon", message: "Poruka",
    subject: "Upit – AirportTransfers Cirih",
  },
  routesSec: {
    eyebrow: "Rute", title: "Popularne rute",
    sub: "Naše najčešće rezervisane rute aerodromskog transfera – po garantovanoj fiksnoj ceni.",
    pageTitle: "Rute",
    pageSub: "Sve rute sa aerodroma Cirih (ZRH) – fiksna cena po vozilu, uklj. 60 min. čekanja.",
    from: "od", origin: "Aerodrom Cirih (ZRH)",
    all: "Prikaži sve", allNote: "Drugo odredište? Vozimo po celoj Švajcarskoj – pitajte nas.",
  },
  fleetSec: {
    eyebrow: "Vozila", title: "Naša flota",
    sub: "Negovana, udobna VIP vozila za grupe svih veličina.",
    pageTitle: "Vozila",
    pageSub: "Sva vozila sa profesionalnim vozačem, WiFi-jem i mineralnom vodom.",
    pax: "Putnici", bags: "Prtljag", cta: "Pitajte odmah",
    features: ["Besplatan WiFi", "Mineralna voda", "Dečja sedišta na zahtev", "Praćenje letova"],
  },
  gallerySec: { eyebrow: "Galerija", title: "Galerija", pageTitle: "Galerija", pageSub: "Utisci iz naših vozila i sa naših vožnji.", all: "Prikaži sve" },
  reviewsSec: { eyebrow: "Utisci", title: "Šta kažu naši gosti", sub: "Prava iskustva pravih putnika.", count: "utisaka", list: [
      { text: "Vozač je čekao sa tablom, auto besprekoran. Rezervacija preko WhatsApp-a za minut.", name: "Nikola J.", route: "ZRH → Zürich City", flag: "🇷🇸" },
      { text: "Let je kasnio 40 minuta – vozač je čekao bez doplate. Pouzdana usluga.", name: "Milica P.", route: "ZRH → Luzern", flag: "🇷🇸" },
      { text: "Fiksna cena ispoštovana do franka. Najbolji transfer u Švajcarskoj.", name: "Stefan M.", route: "ZRH → Bern", flag: "🇷🇸" },
      { text: "Dečje sedište spremno kako smo tražili. Miran put do Interlakena.", name: "Jovana K.", route: "ZRH → Interlaken", flag: "🇷🇸" },
      { text: "Udoban Mercedes, ljubazan vozač. Idealno za poslovna putovanja.", name: "Marko D.", route: "ZRH → Zug", flag: "🇷🇸" },
    ] },
  blogSec: {
    title: "Blog", pageSub: "Saveti za putovanja, vodiči po rutama i korisne informacije o transferima sa aerodroma Cirih.",
    read: "Pročitaj više", minRead: "min. čitanja", more: "Ostali članci", back: "Svi članci", published: "Objavljeno",
  },
  faqPage: {
    title: "Česta pitanja", sub: "Odgovori na najvažnija pitanja o rezervaciji, cenama i toku vožnje.",
    list: [
      ["Kako da rezervišem transfer?", "Najbrže preko asistenta za rezervacije na ovom sajtu ili direktno preko WhatsApp-a. Potvrdu obično dobijate u roku od 15 minuta."],
      ["Da li su cene zaista fiksne?", "Da. Cena navedena pri rezervaciji važi po vozilu i ne menja se – bez obzira na saobraćaj, vreme ili doba dana. Nema noćnih doplata ni doplata za prtljag."],
      ["Šta ako moj let kasni?", "Pratimo vaš let u realnom vremenu i automatski prilagođavamo vreme preuzimanja. Čekanje nakon sletanja je besplatno."],
      ["Gde da nađem vozača na aerodromu?", "Vaš vozač vas čeka sa tablom sa vašim imenom direktno u dolaznoj hali (Meet & Greet) i prati vas do vozila."],
      ["Kako mogu da platim?", "Jednostavno u vozilu: gotovinom, karticom ili preko TWINT-a. Poslovni klijenti na zahtev dobijaju zbirnu fakturu."],
      ["Mogu li besplatno da otkažem?", "Da, do 24 sata pre planiranog preuzimanja otkazivanje je besplatno uz pun povraćaj novca."],
      ["Da li su dostupna dečja sedišta?", "Da, nosiljke za bebe i dečja sedišta obezbeđujemo besplatno. Samo navedite broj i uzrast dece pri rezervaciji."],
      ["Da li prevozite skije i poseban prtljag?", "Torbe za skije prevozimo besplatno (najviše 4 po vozilu). Kabasti prtljag, poput torbi za golf ili kolica, najbolje je najaviti pri rezervaciji."],
    ],
  },
  booking: { title: "Rezervacija", steps: ["Ruta i vreme", "Vozilo", "Kontakt i plaćanje"], route: "Ruta", choose: "Izaberite odredište …", next: "Dalje" },
  detail: {
    selectCar: "Izaberite vozilo", summary: "Pregled vožnje",
    pickupLoc: "Mesto preuzimanja", dropoffLoc: "Odredište", distance: "Ukupna razdaljina", time: "Ukupno vreme",
    vehicle: "Izabrano vozilo", priceNote: "Sve cene uključuju PDV i takse.", select: "Izaberi",
    feats: ["Meet & Greet uključen", "Besplatno otkazivanje", "Besplatno čekanje", "Bezbedna i pouzdana vožnja"],
    noticeTitle: "Važna napomena", noticeText: "Rezervacije napravljene manje od 2 sata pre preuzimanja ne mogu se garantovati u špicu. Molimo rezervišite na vreme.",
    payTitle: "Izaberite način plaćanja",
    payOptions: [["TWINT", "Plaćanje TWINT-om u vozilu"], ["Gotovina", "Plaćanje gotovinom u vozilu"], ["Kreditna kartica", "Plaćanje karticom u vozilu"]],
    paxTitle: "Podaci o putnicima", name: "Ime", surname: "Prezime", email: "E-pošta", phone: "Telefon",
    baby: ["Nosiljka za bebe", "Za bebe 0–13 kg (oko 0–4 godine)."],
    child: ["Dečje sedište", "Za decu 15–36 kg (oko 4–12 godina)."],
    ski: ["Torba za skije", "Bezbedan prevoz opreme (najviše 4 po vozilu)."],
    free: "Besplatno", flight: "Broj leta", nameboard: "Tabla sa imenom (opciono)", luggage: "Prtljag",
    notes: "Poruka vozaču (opciono)", accept: "Prihvatam uslove rezervacije.", back: "Nazad",
    continueWa: "Zatražite rezervaciju preko WhatsApp-a", continueMail: "…ili zatražite e-poštom",
    confirmNote: "Potvrdu obično dobijate u roku od 15 minuta.", total: "Ukupno",
    notFound: "Ruta nije pronađena.", allRoutes: "Sve rute",
  },
  kontakt: {
    title: "Kontakt", formTitle: "Pošaljite poruku",
    name: "Vaše ime", email: "E-pošta", phone: "Telefon", message: "Poruka",
    send: "Pošalji", orMail: "…ili nam pišite direktno e-poštom", infoTitle: "Kontaktirajte nas",
    lblPhone: "Telefon", lblEmail: "E-pošta", lblWa: "WhatsApp", lblAddress: "Adresa",
    lblHours: "Radno vreme", always: "Dostupni 24 časa dnevno",
  },
  footer: {
    popular: "Popularne rute", aboutLink: "O nama", information: "Informacije",
    about: "VIP Mercedes transferi u Cirihu. Fiksne cene, obučeni vozači i praćenje letova – 24 časa dnevno.",
    follow: "Pratite nas", explore: "Istražite", company: "Kompanija", support: "Podrška",
    callUs: "Pozovite nas", writeUs: "Pišite nam", address: "Adresa",
    about2: "O nama", faq: "Česta pitanja", rights: "Sva prava zadržana.", watermark: "Cirih",
  },
};

const tx: DictX = {
  nav: { destinations: "Destinacije", prices: "Cene", events: "Događaji" },
  heroBadges: ["Besplatno otkazivanje", "Podrška 24/7", "Praćenje letova", "Meet & Greet"],
  heroRating: { score: "Odlično · 4.8/5", sub: "Izbor putnika na aerodromu Cirih" },
  howSec: {
    eyebrow: "Kako funkcioniše", title: "Rezervišite u tri jednostavna koraka",
    steps: [
      ["Unesite rutu i izaberite vozilo", "Navedite preuzimanje, odredište i vreme – zatim izaberite odgovarajuće vozilo."],
      ["Završite rezervaciju", "Dodajte kontakt podatke i dobijte potvrdu sa svim detaljima."],
      ["Sretnite svog vozača", "Vozač vas čeka sa tablom sa vašim imenom – čekanje je uključeno."],
    ],
    cta: "Saznajte cenu",
  },
  faqSec: { eyebrow: "FAQ", title: "Česta pitanja", sub: "Sve što treba da znate o rezervaciji, na jednom mestu.", all: "Sva pitanja" },
  hourly: {
    tabTransfer: "Transfer", tabHourly: "Po satu", duration: "Trajanje", hoursShort: "sati",
    note: "Vozač i vozilo na raspolaganju – idealno za sastanke, događaje i obilaske grada.",
    cta: "Pogledajte cene", bookingLabel: "Najam po satu",
    bookingNote: (h: string) => `Rezervacija po satu: ${h} sati – vozač na raspolaganju`,
  },
  stops: { add: "Dodaj stajanje", ph: "Usputna stanica – adresa", remove: "Ukloni", label: "Usputne stanice:" },
  done: { title: "Zahtev poslat!", body: (r: string) => `Vaš zahtev za transfer ${r} je kreiran i otvoren u WhatsApp-u ili e-pošti. Pošaljite poruku – obično potvrđujemo u roku od 15 minuta.`, hint: "Hvala na zahtevu! Proverite i prijemno sanduče ili spam fasciklu.", payment: "Način plaćanja", home: "Nazad na početnu" },
  dest: {
    crumb: "Destinacije",
    pageTitle: "Transferi po celoj Švajcarskoj",
    pageSub: "Sa aerodroma Cirih do svakog grada i planinskog sela. Izaberite destinaciju ili rezervišite direktno.",
    popular: "Popularna mesta", searchPh: "Pretražite mesto …",
    fixed: "od CHF", onRequest: "Cena na upit",
    hero: (n: string) => `Aerodromski transfer ${n}`,
    heroSub: (n: string) => `Privatni vozač i aerodromski transfer do i od ${n}. Fiksna cena po vozilu, obučeni vozači i praćenje letova – 24 časa dnevno.`,
    chips: ["Fiksna cena", "Praćenje letova", "24/7", "Licencirani vozači"],
    calc: "Izračunaj cenu",
    f1: ["Fiksne cene", "Cena je poznata pre vožnje – bez iznenađenja."],
    f2: ["Uvek na vreme", "Pratimo vaš let i prilagođavamo vreme preuzimanja."],
    f3: ["Bezbedno i licencirano", "Obučeni vozači, negovana Mercedes vozila."],
    vehiclesFor: (n: string) => `Vozila za ${n}`,
    routeKnown: (n: string, p: string) => `Fiksna cena aerodrom Cirih → ${n}: od CHF ${p} po vozilu.`,
    routeDetail: "Pogledajte rutu detaljno",
    seo: (n: string, r: string) => [
      [`Aerodromski taksi ${n} po fiksnoj ceni`, `Tražite pouzdan aerodromski transfer za ${n}? Kod nas rezervišete privatni transfer do i od aerodroma Cirih (ZRH) po garantovanoj fiksnoj ceni po vozilu. Bez taksimetra, bez skrivenih doplata: cena je poznata već pri rezervaciji, bez obzira na saobraćaj ili doba dana.`],
      [`Sa aerodroma Cirih (ZRH) do ${n}`, `Vozač vas čeka sa tablom sa vašim imenom direktno u dolaznoj hali (Meet & Greet) i pomaže sa prtljagom. Za povratak iz regiona ${r} uračunavamo saobraćaj i vreme za prijavu, da na aerodrom stignete opušteno i na vreme.`],
      [`24/7 uz praćenje letova`, `Pratimo vaš let u realnom vremenu. Ako avion sleti ranije ili kasnije, vreme preuzimanja se automatski prilagođava – čekanje nakon sletanja uključeno je u fiksnu cenu. Radimo 365 dana u godini.`],
      [`Pravo vozilo za svaku priliku`, `Poslovni put, porodični odmor ili skijanje: od Business klase do prostranog kombija sa do 7 mesta, naći ćete odgovarajuće vozilo za transfer do ${n}. Dečja sedišta i nosiljke su besplatni.`],
    ],
    faqTitle: (n: string) => `Česta pitanja o transferu za ${n}`,
    faq: (n: string) => [
      [`Koliko košta aerodromski taksi za ${n}?`, `Cena je fiksna po vozilu i zavisi od udaljenosti od aerodroma Cirih i klase vozila. Zatražite ponudu za nekoliko sekundi – fiksnu cenu dobijate pre vožnje.`],
      [`Kako da rezervišem transfer za ${n}?`, `Unesite adresu, izaberite datum i vreme, dodajte broj leta – gotovo. Rezervacija traje manje od minuta, onlajn ili preko WhatsApp-a.`],
      ["Da li je praćenje letova uključeno?", "Da. Pratimo svaki let i automatski prilagođavamo vreme preuzimanja. Čekanje nakon sletanja uključeno je u cenu."],
      ["Mogu li besplatno da otkažem?", "Da, otkazivanje je besplatno do 24 sata pre planiranog preuzimanja."],
    ],
    more: "Ostale destinacije", all: "Sva mesta",
    ctaTitle: "Spremni da stignete opušteno?",
    ctaSub: "Dobijte fiksnu, transparentnu cenu za nekoliko sekundi – bez naloga.",
    ctaBtn: "Rezerviši odmah",
  },
  prices: {
    crumb: "Cene", title: "Transparentne fiksne cene",
    sub: "Svaka vožnja po fiksnoj ceni po vozilu – uklj. 60 min. čekanja na aerodromu, Meet & Greet i praćenje letova. Bez skrivenih troškova.",
    f1: ["Garantovana fiksna cena", "Cena se fiksira pri rezervaciji."],
    f2: ["Praćenje letova", "Besplatno čekanje u slučaju kašnjenja."],
    f3: ["Sve uključeno", "Porezi, putarine i Meet & Greet uključeni."],
    classesTitle: "Naše klase vozila i cene",
    from: "od", perVehicle: "po vozilu", book: "Rezerviši",
    tableTitle: "Fiksne cene po rutama",
    tableSub: "Sve rute sa aerodroma Cirih (ZRH) – cena po vozilu, ne po osobi.",
    colDest: "Odredište", colKm: "Razdaljina", colDur: "Trajanje",
    destTitle: "Cene po destinacijama",
    destSub: "Više od 250 mesta u Švajcarskoj i susednim regionima. Izaberite destinaciju za detalje.",
    request: "Na upit",
  },
  events: {
    crumb: "Događaji", title: "Događaji u Švajcarskoj – vaš privatni transfer",
    sub: "Rezervišite vozača za najpoznatije sajmove, festivale i panoramska putovanja Švajcarske.",
    all: "Svi", book: "Rezerviši transfer",
  },
};

export const sr = { t, tx };
