import type { Dict } from "../i18n";
import type { DictX } from "../i18nX";
import { REVIEWS } from "./shared";

const t: Dict = {
  meta: { title: "AirportTransfers Zürih | ZRH Havalimanı Transferi · VIP Mercedes", desc: "Zürih Havalimanı'ndan sabit fiyatlı özel transfer. Eğitimli şoförler, uçuş takibi, 7/24." },
  topbar: "Zürih · Özel Transfer",
  nav: { routes: "Güzergâhlar", fleet: "Araçlar", gallery: "Galeri", contact: "İletişim", book: "Hemen rezervasyon", home: "Ana sayfa" },
  hero: {
    eyebrow: "Zürih · VIP Mercedes", title1: "Zürih Transferleri", title2: "VIP Mercedes ile",
    sub: "Sabit fiyat · Eğitimli şoförler · Uçuş takibi · 7/24 destek",
    pills: ["Sabit fiyat", "7/24 destek", "Anında onay"],
    cta1: "Hemen rezervasyon", cta2: "Popüler güzergâhlar",
  },
  form: {
    title: "Transfer talep edin",
    from: "Alınış noktası", fromPh: "örn. Zürih Havalimanı, Basel …",
    to: "Varış noktası", toPh: "örn. Zermatt, St. Moritz …",
    date: "Tarih", time: "Saat", pax: "Yolcu", kids: "Çocuk",
    wa: "WhatsApp ile talep et", callNow: "Hemen arayın", callSub: "7/24 ulaşılabilir", mail: "E-posta ile talep et",
    search: "Ara", note: "Ücretsiz çocuk koltuğu · Ek ücret yok",
  },
  msg: {
    title: "Rezervasyon talebi – Zürih Havalimanı Transferi", contactTitle: "İletişim talebi – Web sitesi",
    from: "Alınış", to: "Varış", date: "Tarih", time: "Saat", pax: "Yolcu", kids: "Çocuk",
    name: "Ad", email: "E-posta", phone: "Telefon", message: "Mesaj",
    subject: "Talep – AirportTransfers Zürih",
  },
  routesSec: {
    eyebrow: "Güzergâhlar", title: "Popüler güzergâhlar",
    sub: "En çok rezerve edilen havalimanı transfer güzergâhlarımız – garantili sabit fiyatla.",
    pageTitle: "Güzergâhlar",
    pageSub: "Zürih Havalimanı (ZRH) çıkışlı tüm güzergâhlar – araç başına sabit fiyat, 60 dk. bekleme dahil.",
    from: "itibaren", origin: "Zürih Havalimanı (ZRH)",
    all: "Tümünü gör", allNote: "Başka bir varış noktası mı? Tüm İsviçre'ye gidiyoruz – bize sorun.",
  },
  fleetSec: {
    eyebrow: "Araçlar", title: "Filomuz",
    sub: "Her grup için bakımlı, konforlu VIP araçlar.",
    pageTitle: "Araçlar",
    pageSub: "Tüm araçlarda profesyonel şoför, WiFi ve maden suyu.",
    pax: "Yolcu", bags: "Bagaj", cta: "Hemen sorun",
    features: ["Ücretsiz WiFi", "Maden suyu", "İsteğe bağlı çocuk koltuğu", "Uçuş takibi"],
  },
  gallerySec: { eyebrow: "Galeri", title: "Galeri", pageTitle: "Galeri", pageSub: "Araçlarımızdan ve yolculuklarımızdan kareler.", all: "Tümünü gör" },
  reviewsSec: { eyebrow: "Yorumlar", title: "Misafirlerimiz ne diyor", sub: "Gerçek yolculardan gerçek deneyimler.", count: "yorum", list: REVIEWS },
  blogSec: {
    title: "Blog", pageSub: "Zürih Havalimanı transferleri hakkında seyahat ipuçları, güzergâh rehberleri ve faydalı bilgiler.",
    read: "Devamını oku", minRead: "dk. okuma", more: "Diğer yazılar", back: "Tüm yazılar", published: "Yayın tarihi",
  },
  faqPage: {
    title: "Sıkça sorulan sorular", sub: "Rezervasyon, fiyatlar ve işleyişle ilgili en önemli soruların yanıtları.",
    list: [
      ["Nasıl rezervasyon yapabilirim?", "En hızlısı bu sitedeki rezervasyon asistanı ya da doğrudan WhatsApp. Onayınız genellikle 15 dakika içinde gelir."],
      ["Fiyatlar gerçekten sabit mi?", "Evet. Rezervasyonda belirtilen fiyat araç başınadır ve değişmez – trafik, hava ya da saatten bağımsız. Gece veya bagaj ek ücreti yoktur."],
      ["Uçağım rötar yaparsa ne olur?", "Uçuşunuzu gerçek zamanlı takip eder, alınış saatini otomatik ayarlarız. İnişten sonraki bekleme ücretsizdir."],
      ["Şoförümle havalimanında nerede buluşacağım?", "Şoförünüz, geliş salonunda isim tabelasıyla sizi bekler (Meet & Greet) ve araca kadar eşlik eder."],
      ["Nasıl ödeme yapabilirim?", "Araçta rahatça: nakit, kredi kartı veya TWINT. Kurumsal müşterilere talep hâlinde toplu fatura düzenlenir."],
      ["Ücretsiz iptal edebilir miyim?", "Evet, planlanan alınıştan 24 saat öncesine kadar ücretsiz iptal edebilir ve tam iade alırsınız."],
      ["Çocuk koltuğu var mı?", "Evet, bebek ve çocuk koltuklarını ücretsiz sağlıyoruz. Rezervasyonda çocuk sayısını ve yaşlarını belirtmeniz yeterli."],
      ["Kayak ve özel bagaj taşıyor musunuz?", "Kayak çantaları ücretsiz taşınır (araç başına en fazla 4). Golf çantası veya bebek arabası gibi büyük bagajları rezervasyonda belirtmenizi öneririz."],
    ],
  },
  booking: { title: "Rezervasyon", steps: ["Güzergâh ve saat", "Araç", "İletişim ve ödeme"], route: "Güzergâh", choose: "Lütfen varış noktası seçin …", next: "Devam" },
  detail: {
    selectCar: "Aracınızı seçin", summary: "Yolculuk özeti",
    pickupLoc: "Alınış noktası", dropoffLoc: "Varış noktası", distance: "Toplam mesafe", time: "Toplam süre",
    vehicle: "Seçilen araç", priceNote: "Tüm fiyatlara KDV ve ücretler dahildir.", select: "Seç",
    feats: ["Meet & Greet dahil", "Ücretsiz iptal", "Ücretsiz bekleme", "Güvenli ve konforlu yolculuk"],
    noticeTitle: "Önemli rezervasyon notu", noticeText: "Alınış saatine 2 saatten az kala yapılan rezervasyonlar yoğun saatlerde garanti edilemeyebilir. Lütfen erken rezervasyon yapın.",
    payTitle: "Ödeme yöntemini seçin",
    payOptions: [["TWINT", "Araçta TWINT ile ödeme"], ["Nakit", "Araçta nakit ödeme"], ["Kredi kartı", "Araçta kartla ödeme"]],
    paxTitle: "Yolcu bilgileri", name: "Ad", surname: "Soyad", email: "E-posta", phone: "Telefon",
    baby: ["Bebek koltuğu", "0–13 kg bebekler için (yakl. 0–4 yaş)."],
    child: ["Çocuk koltuğu", "15–36 kg çocuklar için (yakl. 4–12 yaş)."],
    ski: ["Kayak çantası", "Ekipmanın güvenli taşınması (araç başına en fazla 4)."],
    free: "Ücretsiz", flight: "Uçuş numarası", nameboard: "İsim tabelası (isteğe bağlı)", luggage: "Bagaj",
    notes: "Şoföre not (isteğe bağlı)", accept: "Rezervasyon koşullarını kabul ediyorum.", back: "Geri",
    continueWa: "WhatsApp ile rezervasyon talebi", continueMail: "…veya e-posta ile talep et",
    confirmNote: "Onayınız genellikle 15 dakika içinde gelir.", total: "Toplam",
    notFound: "Güzergâh bulunamadı.", allRoutes: "Tüm güzergâhlar",
  },
  kontakt: {
    title: "İletişim", formTitle: "Mesaj gönderin",
    name: "Adınız", email: "E-posta", phone: "Telefon", message: "Mesaj",
    send: "Gönder", orMail: "…veya doğrudan e-posta ile yazın", infoTitle: "Bize ulaşın",
    lblPhone: "Telefon", lblEmail: "E-posta", lblWa: "WhatsApp", lblAddress: "Adres",
    lblHours: "Çalışma saatleri", always: "7/24 ulaşılabilir",
  },
  footer: {
    popular: "Popüler güzergâhlar", aboutLink: "Hakkımızda", information: "Bilgi",
    about: "Zürih'te VIP Mercedes transferleri. Sabit fiyatlar, eğitimli şoförler ve uçuş takibi – 7/24.",
    follow: "Bizi takip edin", explore: "Keşfet", company: "Şirket", support: "Destek",
    callUs: "Bizi arayın", writeUs: "Bize yazın", address: "Adres",
    about2: "Hakkımızda", faq: "Sıkça sorulan sorular", rights: "Tüm hakları saklıdır.", watermark: "Zürih",
  },
};

const tx: DictX = {
  nav: { destinations: "Destinasyonlar", prices: "Fiyatlar", events: "Etkinlikler" },
  heroBadges: ["Ücretsiz iptal", "7/24 destek", "Uçuş takibi", "Meet & Greet"],
  heroRating: { score: "Mükemmel · 4.8/5", sub: "Zürih Havalimanı yolcularının tercihi" },
  howSec: {
    eyebrow: "Nasıl çalışır", title: "Üç kolay adımda rezervasyon",
    steps: [
      ["Güzergâhı girin ve aracı seçin", "Alınış, varış ve saati belirtin – sonra size uygun aracı seçin."],
      ["Rezervasyonu tamamlayın", "İletişim bilgilerinizi ekleyin, tüm detaylarıyla onayınızı alın."],
      ["Şoförünüzle buluşun", "Şoförünüz isim tabelasıyla sizi bekler – bekleme süresi dahildir."],
    ],
    cta: "Fiyat alın",
  },
  faqSec: { eyebrow: "SSS", title: "Sıkça sorulan sorular", sub: "Rezervasyonunuzla ilgili bilmeniz gereken her şey bir bakışta.", all: "Tüm soruları gör" },
  hourly: {
    tabTransfer: "Transfer", tabHourly: "Saatlik", duration: "Süre", hoursShort: "saat",
    note: "Şoför ve araç emrinize amade – toplantılar, etkinlikler ve şehir turları için ideal.",
    cta: "Fiyatları gör", bookingLabel: "Saatlik kiralama",
    bookingNote: (h: string) => `Saatlik rezervasyon: ${h} saat – şoför emrinizde`,
  },
  dest: {
    crumb: "Destinasyonlar",
    pageTitle: "Tüm İsviçre'ye transfer",
    pageSub: "Zürih Havalimanı'ndan her şehre ve her dağ köyüne. Destinasyonunuzu seçin veya doğrudan rezervasyon yapın.",
    popular: "Popüler yerler", searchPh: "Yer arayın …",
    fixed: "CHF'den itibaren", onRequest: "Fiyat sorunuz",
    hero: (n: string) => `${n} havalimanı transferi`,
    heroSub: (n: string) => `${n} yönüne ve yönünden özel şoför ve havalimanı transfer hizmeti. Araç başına sabit fiyat, eğitimli şoförler ve uçuş takibi – 7/24.`,
    chips: ["Sabit fiyat", "Uçuş takibi", "7/24", "Lisanslı şoförler"],
    calc: "Fiyat hesapla",
    f1: ["Sabit fiyatlar", "Fiyatınız yolculuktan önce bellidir – sürpriz yok."],
    f2: ["Her zaman dakik", "Uçuşunuzu izler, alınış saatini ayarlarız."],
    f3: ["Güvenli ve lisanslı", "Eğitimli şoförler, bakımlı Mercedes araçlar."],
    vehiclesFor: (n: string) => `${n} için araçlar`,
    routeKnown: (n: string, p: string) => `Zürih Havalimanı → ${n} sabit fiyat: araç başına CHF ${p}'den itibaren.`,
    routeDetail: "Güzergâhı detaylı görüntüle",
    seo: (n: string, r: string) => [
      [`Sabit fiyatlı ${n} havalimanı taksisi`, `${n} için güvenilir bir havalimanı transferi mi arıyorsunuz? Zürih Havalimanı (ZRH) yönüne ve yönünden özel transferinizi araç başına garantili sabit fiyatla bizden rezerve edin. Taksimetre yok, gizli ek ücret yok: fiyat, trafikten veya saatten bağımsız olarak rezervasyon anında bellidir.`],
      [`Zürih Havalimanı'ndan (ZRH) ${n} yönüne`, `Şoförünüz, geliş salonunda isim tabelasıyla sizi karşılar (Meet & Greet) ve bagajlarınıza yardım eder. ${r} bölgesinden dönüş yolculuğunda trafiği ve check-in sürelerini hesaba katarız; havalimanına rahat ve zamanında varırsınız.`],
      [`Uçuş takibiyle 7/24`, `Uçuşunuzu gerçek zamanlı izleriz. Uçağınız erken veya geç inerse alınış saati otomatik güncellenir – inişten sonraki bekleme sabit fiyata dahildir. Hizmetimiz yılın 365 günü aktiftir.`],
      [`Her durum için doğru araç`, `İş seyahati, aile tatili veya kayak haftası: Business Class'tan 7 kişilik geniş minivana kadar, ${n} transferiniz için uygun aracı bulursunuz. Çocuk ve bebek koltukları ücretsizdir.`],
    ],
    faqTitle: (n: string) => `${n} transferi hakkında sık sorulanlar`,
    faq: (n: string) => [
      [`${n} havalimanı taksisi ne kadar?`, `Fiyat araç başına sabittir; Zürih Havalimanı'na uzaklığa ve araç sınıfına göre belirlenir. Saniyeler içinde teklif isteyin – sabit fiyatı yolculuktan önce alırsınız.`],
      [`${n} transferimi nasıl rezerve ederim?`, `Adresinizi girin, tarih ve saati seçin, uçuş numaranızı ekleyin – bitti. Rezervasyon bir dakikadan kısa sürer; online veya WhatsApp ile.`],
      ["Uçuş takibi dahil mi?", "Evet. Her uçuşu izler, alınış saatini otomatik ayarlarız. İnişten sonraki bekleme fiyata dahildir."],
      ["Ücretsiz iptal edebilir miyim?", "Evet, planlanan alınıştan 24 saat öncesine kadar iptal ücretsizdir."],
    ],
    more: "Diğer destinasyonlar", all: "Tüm yerler",
    ctaTitle: "Rahat bir varışa hazır mısınız?",
    ctaSub: "Saniyeler içinde sabit, şeffaf bir fiyat alın – hesap açmanıza gerek yok.",
    ctaBtn: "Hemen rezervasyon",
  },
  prices: {
    crumb: "Fiyatlar", title: "Şeffaf sabit fiyatlar",
    sub: "Her yolculuk araç başına sabit fiyatla – havalimanında 60 dk. bekleme, Meet & Greet ve uçuş takibi dahil. Gizli ücret yok.",
    f1: ["Sabit fiyat garantisi", "Fiyat rezervasyonda sabitlenir."],
    f2: ["Uçuş takibi", "Rötar hâlinde ücretsiz bekleme."],
    f3: ["Her şey dahil", "Vergiler, geçiş ücretleri ve Meet & Greet dahildir."],
    classesTitle: "Araç sınıflarımız ve fiyatları",
    from: "itibaren", perVehicle: "araç başına", book: "Rezervasyon",
    tableTitle: "Güzergâha göre sabit fiyatlar",
    tableSub: "Zürih Havalimanı (ZRH) çıkışlı tüm güzergâhlar – fiyat kişi başına değil, araç başınadır.",
    colDest: "Varış", colKm: "Mesafe", colDur: "Süre",
    destTitle: "Destinasyona göre fiyatlar",
    destSub: "İsviçre ve komşu bölgelerde 250'den fazla yer. Detaylar için destinasyonunuzu seçin.",
    request: "Sorunuz",
  },
  events: {
    crumb: "Etkinlikler", title: "İsviçre'de etkinlikler – özel transferiniz",
    sub: "İsviçre'nin en bilinen fuarları, festivalleri ve panoramik yolculukları için şoförünüzü ayırtın.",
    all: "Tümü", book: "Transfer rezervasyonu",
  },
};

export const tr = { t, tx };
