// ─────────────────────────────────────────────────────────────
//  REISEZIELE / DESTINATIONS — bölge bölge tüm varış yerleri
//  Sabit fiyatlı rotayla eşleşenler routeSlug taşır; diğerleri
//  "fiyat sorunuz" akışıyla rezervasyona yönlenir.
// ─────────────────────────────────────────────────────────────

export type Destination = { name: string; slug: string; routeSlug?: string };
export type DestRegion = { key: string; label: { de: string; en: string }; cities: Destination[] };

export const destRegions: DestRegion[] = [
  { key: "popular", label: { de: "Beliebte Orte", en: "Popular places" }, cities: [
    { name: "Zürich", slug: "flughafentransfer-zuerich" },
    { name: "Genève", slug: "flughafentransfer-geneve", routeSlug: "zurich-airport-to-geneva" },
    { name: "Basel", slug: "flughafentransfer-basel", routeSlug: "zurich-airport-to-basel" },
    { name: "Bern", slug: "flughafentransfer-bern", routeSlug: "zurich-airport-to-bern" },
    { name: "Lausanne", slug: "flughafentransfer-lausanne", routeSlug: "zurich-airport-to-lausanne" },
    { name: "Luzern", slug: "flughafentransfer-luzern", routeSlug: "zurich-airport-to-luzern" },
    { name: "Davos", slug: "flughafentransfer-davos", routeSlug: "zurich-airport-to-davos" },
    { name: "St. Moritz", slug: "flughafentransfer-st-moritz", routeSlug: "zurich-airport-to-st-moritz" },
    { name: "Zermatt", slug: "flughafentransfer-zermatt", routeSlug: "zurich-airport-to-zermatt" },
    { name: "Interlaken", slug: "flughafentransfer-interlaken", routeSlug: "zurich-airport-to-interlaken" },
    { name: "Lugano", slug: "flughafentransfer-lugano", routeSlug: "zurich-airport-to-lugano" },
    { name: "St. Gallen", slug: "flughafentransfer-st-gallen", routeSlug: "zurich-airport-to-st-gallen" },
  ] },
  { key: "zuerich", label: { de: "Kanton Zürich", en: "Canton of Zurich" }, cities: [
    { name: "Winterthur", slug: "flughafentransfer-winterthur", routeSlug: "zurich-airport-to-winterthur" },
    { name: "Uster", slug: "flughafentransfer-uster" },
    { name: "Dübendorf", slug: "flughafentransfer-duebendorf" },
    { name: "Dietikon", slug: "flughafentransfer-dietikon" },
    { name: "Wetzikon", slug: "flughafentransfer-wetzikon" },
    { name: "Wädenswil", slug: "flughafentransfer-waedenswil" },
    { name: "Horgen", slug: "flughafentransfer-horgen" },
    { name: "Kloten", slug: "flughafentransfer-kloten" },
    { name: "Bülach", slug: "flughafentransfer-buelach" },
    { name: "Opfikon", slug: "flughafentransfer-opfikon" },
    { name: "Regensdorf", slug: "flughafentransfer-regensdorf" },
    { name: "Illnau-Effretikon", slug: "flughafentransfer-illnau-effretikon" },
    { name: "Volketswil", slug: "flughafentransfer-volketswil" },
    { name: "Schlieren", slug: "flughafentransfer-schlieren" },
    { name: "Adliswil", slug: "flughafentransfer-adliswil" },
    { name: "Thalwil", slug: "flughafentransfer-thalwil" },
    { name: "Meilen", slug: "flughafentransfer-meilen" },
    { name: "Küsnacht", slug: "flughafentransfer-kuesnacht" },
    { name: "Zollikon", slug: "flughafentransfer-zollikon" },
    { name: "Rüti", slug: "flughafentransfer-rueti" },
  ] },
  { key: "bern", label: { de: "Kanton Bern", en: "Canton of Bern" }, cities: [
    { name: "Thun", slug: "flughafentransfer-thun", routeSlug: "zurich-airport-to-thun" },
    { name: "Biel/Bienne", slug: "flughafentransfer-biel-bienne" },
    { name: "Köniz", slug: "flughafentransfer-koeniz" },
    { name: "Steffisburg", slug: "flughafentransfer-steffisburg" },
    { name: "Burgdorf", slug: "flughafentransfer-burgdorf" },
    { name: "Langenthal", slug: "flughafentransfer-langenthal" },
    { name: "Spiez", slug: "flughafentransfer-spiez" },
    { name: "Münsingen", slug: "flughafentransfer-muensingen" },
    { name: "Lyss", slug: "flughafentransfer-lyss" },
    { name: "Grindelwald", slug: "flughafentransfer-grindelwald", routeSlug: "zurich-airport-to-grindelwald" },
    { name: "Wengen", slug: "flughafentransfer-wengen", routeSlug: "zurich-airport-to-wengen" },
    { name: "Gstaad", slug: "flughafentransfer-gstaad" },
    { name: "Adelboden", slug: "flughafentransfer-adelboden" },
    { name: "Zweisimmen", slug: "flughafentransfer-zweisimmen" },
    { name: "Meiringen", slug: "flughafentransfer-meiringen" },
    { name: "Ittigen", slug: "flughafentransfer-ittigen" },
    { name: "Muri bei Bern", slug: "flughafentransfer-muri-bei-bern" },
    { name: "Worb", slug: "flughafentransfer-worb" },
    { name: "Belp", slug: "flughafentransfer-belp" },
    { name: "Saanen", slug: "flughafentransfer-saanen" },
    { name: "Lauterbrunnen", slug: "flughafentransfer-lauterbrunnen" },
    { name: "Mürren", slug: "flughafentransfer-muerren" },
    { name: "Brienz", slug: "flughafentransfer-brienz" },
    { name: "Frutigen", slug: "flughafentransfer-frutigen" },
    { name: "Kandersteg", slug: "flughafentransfer-kandersteg" },
  ] },
  { key: "luzern", label: { de: "Kanton Luzern", en: "Canton of Lucerne" }, cities: [
    { name: "Emmen", slug: "flughafentransfer-emmen" },
    { name: "Kriens", slug: "flughafentransfer-kriens" },
    { name: "Horw", slug: "flughafentransfer-horw" },
    { name: "Ebikon", slug: "flughafentransfer-ebikon" },
    { name: "Sursee", slug: "flughafentransfer-sursee" },
    { name: "Hochdorf", slug: "flughafentransfer-hochdorf" },
    { name: "Willisau", slug: "flughafentransfer-willisau" },
    { name: "Weggis", slug: "flughafentransfer-weggis" },
    { name: "Vitznau", slug: "flughafentransfer-vitznau" },
    { name: "Meggen", slug: "flughafentransfer-meggen" },
    { name: "Malters", slug: "flughafentransfer-malters" },
    { name: "Rothenburg", slug: "flughafentransfer-rothenburg" },
    { name: "Ruswil", slug: "flughafentransfer-ruswil" },
    { name: "Schötz", slug: "flughafentransfer-schoetz" },
    { name: "Wolhusen", slug: "flughafentransfer-wolhusen" },
  ] },
  { key: "uri", label: { de: "Kanton Uri", en: "Canton of Uri" }, cities: [
    { name: "Altdorf", slug: "flughafentransfer-altdorf" },
    { name: "Erstfeld", slug: "flughafentransfer-erstfeld" },
    { name: "Schattdorf", slug: "flughafentransfer-schattdorf" },
    { name: "Bürglen", slug: "flughafentransfer-buerglen" },
    { name: "Andermatt", slug: "flughafentransfer-andermatt" },
    { name: "Flüelen", slug: "flughafentransfer-flueelen" },
    { name: "Silenen", slug: "flughafentransfer-silenen" },
    { name: "Wassen", slug: "flughafentransfer-wassen" },
  ] },
  { key: "schwyz", label: { de: "Kanton Schwyz", en: "Canton of Schwyz" }, cities: [
    { name: "Schwyz", slug: "flughafentransfer-schwyz" },
    { name: "Einsiedeln", slug: "flughafentransfer-einsiedeln" },
    { name: "Freienbach", slug: "flughafentransfer-freienbach" },
    { name: "Küssnacht", slug: "flughafentransfer-kuessnacht" },
    { name: "Arth", slug: "flughafentransfer-arth" },
    { name: "Goldau", slug: "flughafentransfer-goldau" },
    { name: "Lachen", slug: "flughafentransfer-lachen" },
    { name: "Pfäffikon SZ", slug: "flughafentransfer-pfaeffikon-sz" },
    { name: "Brunnen", slug: "flughafentransfer-brunnen" },
    { name: "Ibach", slug: "flughafentransfer-ibach" },
    { name: "Wollerau", slug: "flughafentransfer-wollerau" },
  ] },
  { key: "obwalden", label: { de: "Kanton Obwalden", en: "Canton of Obwalden" }, cities: [
    { name: "Sarnen", slug: "flughafentransfer-sarnen" },
    { name: "Kerns", slug: "flughafentransfer-kerns" },
    { name: "Sachseln", slug: "flughafentransfer-sachseln" },
    { name: "Alpnach", slug: "flughafentransfer-alpnach" },
    { name: "Engelberg", slug: "flughafentransfer-engelberg" },
    { name: "Giswil", slug: "flughafentransfer-giswil" },
    { name: "Lungern", slug: "flughafentransfer-lungern" },
  ] },
  { key: "nidwalden", label: { de: "Kanton Nidwalden", en: "Canton of Nidwalden" }, cities: [
    { name: "Stans", slug: "flughafentransfer-stans" },
    { name: "Hergiswil", slug: "flughafentransfer-hergiswil" },
    { name: "Buochs", slug: "flughafentransfer-buochs" },
    { name: "Beckenried", slug: "flughafentransfer-beckenried" },
    { name: "Emmetten", slug: "flughafentransfer-emmetten" },
    { name: "Wolfenschiessen", slug: "flughafentransfer-wolfenschiessen" },
    { name: "Ennetbürgen", slug: "flughafentransfer-ennetbuergen" },
    { name: "Dallenwil", slug: "flughafentransfer-dallenwil" },
  ] },
  { key: "glarus", label: { de: "Kanton Glarus", en: "Canton of Glarus" }, cities: [
    { name: "Glarus", slug: "flughafentransfer-glarus" },
    { name: "Näfels", slug: "flughafentransfer-naefels" },
    { name: "Netstal", slug: "flughafentransfer-netstal" },
    { name: "Ennenda", slug: "flughafentransfer-ennenda" },
    { name: "Mollis", slug: "flughafentransfer-mollis" },
    { name: "Linthal", slug: "flughafentransfer-linthal" },
    { name: "Schwanden", slug: "flughafentransfer-schwanden" },
    { name: "Braunwald", slug: "flughafentransfer-braunwald" },
  ] },
  { key: "zug", label: { de: "Kanton Zug", en: "Canton of Zug" }, cities: [
    { name: "Zug", slug: "flughafentransfer-zug", routeSlug: "zurich-airport-to-zug" },
    { name: "Baar", slug: "flughafentransfer-baar" },
    { name: "Cham", slug: "flughafentransfer-cham" },
    { name: "Steinhausen", slug: "flughafentransfer-steinhausen" },
    { name: "Rotkreuz", slug: "flughafentransfer-rotkreuz" },
    { name: "Hünenberg", slug: "flughafentransfer-huenenberg" },
    { name: "Unterägeri", slug: "flughafentransfer-unteraegeri" },
    { name: "Oberägeri", slug: "flughafentransfer-oberaegeri" },
    { name: "Menzingen", slug: "flughafentransfer-menzingen" },
    { name: "Neuheim", slug: "flughafentransfer-neuheim" },
    { name: "Walchwil", slug: "flughafentransfer-walchwil" },
  ] },
  { key: "freiburg", label: { de: "Kanton Freiburg", en: "Canton of Fribourg" }, cities: [
    { name: "Fribourg", slug: "flughafentransfer-fribourg", routeSlug: "zurich-airport-to-fribourg" },
    { name: "Bulle", slug: "flughafentransfer-bulle" },
    { name: "Villars-sur-Glâne", slug: "flughafentransfer-villars-sur-glane" },
    { name: "Marly", slug: "flughafentransfer-marly" },
    { name: "Düdingen", slug: "flughafentransfer-duedingen" },
    { name: "Estavayer", slug: "flughafentransfer-estavayer" },
    { name: "Murten", slug: "flughafentransfer-murten" },
    { name: "Kerzers", slug: "flughafentransfer-kerzers" },
    { name: "Romont", slug: "flughafentransfer-romont" },
    { name: "Châtel-St-Denis", slug: "flughafentransfer-chatel-st-denis" },
    { name: "Gruyères", slug: "flughafentransfer-gruyeres" },
    { name: "Charmey", slug: "flughafentransfer-charmey" },
  ] },
  { key: "solothurn", label: { de: "Kanton Solothurn", en: "Canton of Solothurn" }, cities: [
    { name: "Solothurn", slug: "flughafentransfer-solothurn" },
    { name: "Olten", slug: "flughafentransfer-olten" },
    { name: "Grenchen", slug: "flughafentransfer-grenchen" },
    { name: "Zuchwil", slug: "flughafentransfer-zuchwil" },
    { name: "Dornach", slug: "flughafentransfer-dornach" },
    { name: "Balsthal", slug: "flughafentransfer-balsthal" },
    { name: "Oensingen", slug: "flughafentransfer-oensingen" },
    { name: "Derendingen", slug: "flughafentransfer-derendingen" },
    { name: "Biberist", slug: "flughafentransfer-biberist" },
    { name: "Wangen bei Olten", slug: "flughafentransfer-wangen-bei-olten" },
  ] },
  { key: "basel", label: { de: "Region Basel", en: "Basel region" }, cities: [
    { name: "Riehen", slug: "flughafentransfer-riehen" },
    { name: "Bettingen", slug: "flughafentransfer-bettingen" },
    { name: "Liestal", slug: "flughafentransfer-liestal" },
    { name: "Allschwil", slug: "flughafentransfer-allschwil" },
    { name: "Reinach BL", slug: "flughafentransfer-reinach-bl" },
    { name: "Muttenz", slug: "flughafentransfer-muttenz" },
    { name: "Pratteln", slug: "flughafentransfer-pratteln" },
    { name: "Binningen", slug: "flughafentransfer-binningen" },
    { name: "Münchenstein", slug: "flughafentransfer-muenchenstein" },
    { name: "Aesch", slug: "flughafentransfer-aesch" },
    { name: "Sissach", slug: "flughafentransfer-sissach" },
    { name: "Laufen", slug: "flughafentransfer-laufen" },
    { name: "Birsfelden", slug: "flughafentransfer-birsfelden" },
    { name: "Bottmingen", slug: "flughafentransfer-bottmingen" },
  ] },
  { key: "schaffhausen", label: { de: "Kanton Schaffhausen", en: "Canton of Schaffhausen" }, cities: [
    { name: "Schaffhausen", slug: "flughafentransfer-schaffhausen", routeSlug: "zurich-airport-to-schaffhausen" },
    { name: "Neuhausen", slug: "flughafentransfer-neuhausen" },
    { name: "Thayngen", slug: "flughafentransfer-thayngen" },
    { name: "Stein am Rhein", slug: "flughafentransfer-stein-am-rhein" },
    { name: "Beringen", slug: "flughafentransfer-beringen" },
    { name: "Ramsen", slug: "flughafentransfer-ramsen" },
    { name: "Hallau", slug: "flughafentransfer-hallau" },
  ] },
  { key: "appenzell", label: { de: "Appenzellerland", en: "Appenzell region" }, cities: [
    { name: "Herisau", slug: "flughafentransfer-herisau" },
    { name: "Teufen", slug: "flughafentransfer-teufen" },
    { name: "Speicher", slug: "flughafentransfer-speicher" },
    { name: "Heiden", slug: "flughafentransfer-heiden" },
    { name: "Gais", slug: "flughafentransfer-gais" },
    { name: "Urnäsch", slug: "flughafentransfer-urnaesch" },
    { name: "Trogen", slug: "flughafentransfer-trogen" },
    { name: "Appenzell", slug: "flughafentransfer-appenzell" },
    { name: "Oberegg", slug: "flughafentransfer-oberegg" },
    { name: "Gonten", slug: "flughafentransfer-gonten" },
  ] },
  { key: "stgallen", label: { de: "Kanton St. Gallen", en: "Canton of St. Gallen" }, cities: [
    { name: "Rapperswil-Jona", slug: "flughafentransfer-rapperswil-jona" },
    { name: "Wil", slug: "flughafentransfer-wil" },
    { name: "Gossau", slug: "flughafentransfer-gossau" },
    { name: "Buchs SG", slug: "flughafentransfer-buchs-sg" },
    { name: "Uzwil", slug: "flughafentransfer-uzwil" },
    { name: "Altstätten", slug: "flughafentransfer-altstaetten" },
    { name: "Flawil", slug: "flughafentransfer-flawil" },
    { name: "Wattwil", slug: "flughafentransfer-wattwil" },
    { name: "Rorschach", slug: "flughafentransfer-rorschach" },
    { name: "Sargans", slug: "flughafentransfer-sargans" },
    { name: "Bad Ragaz", slug: "flughafentransfer-bad-ragaz" },
    { name: "Widnau", slug: "flughafentransfer-widnau" },
    { name: "Heerbrugg", slug: "flughafentransfer-heerbrugg" },
    { name: "Wildhaus", slug: "flughafentransfer-wildhaus" },
    { name: "Flums", slug: "flughafentransfer-flums" },
  ] },
  { key: "graubuenden", label: { de: "Kanton Graubünden", en: "Canton of Grisons" }, cities: [
    { name: "Chur", slug: "flughafentransfer-chur", routeSlug: "zurich-airport-to-chur" },
    { name: "Landquart", slug: "flughafentransfer-landquart" },
    { name: "Domat/Ems", slug: "flughafentransfer-domat-ems" },
    { name: "Ilanz", slug: "flughafentransfer-ilanz" },
    { name: "Arosa", slug: "flughafentransfer-arosa" },
    { name: "Klosters", slug: "flughafentransfer-klosters" },
    { name: "Pontresina", slug: "flughafentransfer-pontresina" },
    { name: "Flims", slug: "flughafentransfer-flims" },
    { name: "Laax", slug: "flughafentransfer-laax" },
    { name: "Lenzerheide", slug: "flughafentransfer-lenzerheide" },
    { name: "Scuol", slug: "flughafentransfer-scuol" },
    { name: "Samedan", slug: "flughafentransfer-samedan" },
    { name: "Zuoz", slug: "flughafentransfer-zuoz" },
    { name: "Thusis", slug: "flughafentransfer-thusis" },
    { name: "Disentis", slug: "flughafentransfer-disentis" },
    { name: "Savognin", slug: "flughafentransfer-savognin" },
    { name: "Celerina", slug: "flughafentransfer-celerina" },
    { name: "Zernez", slug: "flughafentransfer-zernez" },
    { name: "Splügen", slug: "flughafentransfer-spluegen" },
  ] },
  { key: "aargau", label: { de: "Kanton Aargau", en: "Canton of Aargau" }, cities: [
    { name: "Aarau", slug: "flughafentransfer-aarau" },
    { name: "Baden", slug: "flughafentransfer-baden" },
    { name: "Wettingen", slug: "flughafentransfer-wettingen" },
    { name: "Wohlen", slug: "flughafentransfer-wohlen" },
    { name: "Rheinfelden", slug: "flughafentransfer-rheinfelden" },
    { name: "Zofingen", slug: "flughafentransfer-zofingen" },
    { name: "Brugg", slug: "flughafentransfer-brugg" },
    { name: "Lenzburg", slug: "flughafentransfer-lenzburg" },
    { name: "Oftringen", slug: "flughafentransfer-oftringen" },
    { name: "Buchs AG", slug: "flughafentransfer-buchs-ag" },
    { name: "Suhr", slug: "flughafentransfer-suhr" },
    { name: "Möhlin", slug: "flughafentransfer-moehlin" },
    { name: "Spreitenbach", slug: "flughafentransfer-spreitenbach" },
    { name: "Neuenhof", slug: "flughafentransfer-neuenhof" },
    { name: "Frick", slug: "flughafentransfer-frick" },
    { name: "Menziken", slug: "flughafentransfer-menziken" },
    { name: "Bremgarten", slug: "flughafentransfer-bremgarten" },
    { name: "Kaiseraugst", slug: "flughafentransfer-kaiseraugst" },
    { name: "Klingnau", slug: "flughafentransfer-klingnau" },
    { name: "Muri", slug: "flughafentransfer-muri" },
  ] },
  { key: "thurgau", label: { de: "Kanton Thurgau", en: "Canton of Thurgau" }, cities: [
    { name: "Frauenfeld", slug: "flughafentransfer-frauenfeld" },
    { name: "Kreuzlingen", slug: "flughafentransfer-kreuzlingen" },
    { name: "Arbon", slug: "flughafentransfer-arbon" },
    { name: "Amriswil", slug: "flughafentransfer-amriswil" },
    { name: "Weinfelden", slug: "flughafentransfer-weinfelden" },
    { name: "Romanshorn", slug: "flughafentransfer-romanshorn" },
    { name: "Aadorf", slug: "flughafentransfer-aadorf" },
    { name: "Sirnach", slug: "flughafentransfer-sirnach" },
    { name: "Bischofszell", slug: "flughafentransfer-bischofszell" },
    { name: "Steckborn", slug: "flughafentransfer-steckborn" },
    { name: "Ermatingen", slug: "flughafentransfer-ermatingen" },
  ] },
  { key: "tessin", label: { de: "Kanton Tessin", en: "Canton of Ticino" }, cities: [
    { name: "Bellinzona", slug: "flughafentransfer-bellinzona", routeSlug: "zurich-airport-to-bellinzona" },
    { name: "Locarno", slug: "flughafentransfer-locarno", routeSlug: "zurich-airport-to-locarno" },
    { name: "Mendrisio", slug: "flughafentransfer-mendrisio" },
    { name: "Chiasso", slug: "flughafentransfer-chiasso" },
    { name: "Ascona", slug: "flughafentransfer-ascona" },
    { name: "Losone", slug: "flughafentransfer-losone" },
    { name: "Minusio", slug: "flughafentransfer-minusio" },
    { name: "Biasca", slug: "flughafentransfer-biasca" },
    { name: "Airolo", slug: "flughafentransfer-airolo" },
    { name: "Paradiso", slug: "flughafentransfer-paradiso" },
    { name: "Massagno", slug: "flughafentransfer-massagno" },
    { name: "Giubiasco", slug: "flughafentransfer-giubiasco" },
    { name: "Tenero", slug: "flughafentransfer-tenero" },
    { name: "Faido", slug: "flughafentransfer-faido" },
    { name: "Muralto", slug: "flughafentransfer-muralto" },
  ] },
  { key: "waadt", label: { de: "Kanton Waadt", en: "Canton of Vaud" }, cities: [
    { name: "Montreux", slug: "flughafentransfer-montreux", routeSlug: "zurich-airport-to-montreux" },
    { name: "Yverdon-les-Bains", slug: "flughafentransfer-yverdon-les-bains" },
    { name: "Nyon", slug: "flughafentransfer-nyon" },
    { name: "Vevey", slug: "flughafentransfer-vevey" },
    { name: "Renens", slug: "flughafentransfer-renens" },
    { name: "Morges", slug: "flughafentransfer-morges" },
    { name: "Gland", slug: "flughafentransfer-gland" },
    { name: "Pully", slug: "flughafentransfer-pully" },
    { name: "Prilly", slug: "flughafentransfer-prilly" },
    { name: "Aigle", slug: "flughafentransfer-aigle" },
    { name: "Villars-sur-Ollon", slug: "flughafentransfer-villars-sur-ollon" },
    { name: "Rolle", slug: "flughafentransfer-rolle" },
    { name: "Payerne", slug: "flughafentransfer-payerne" },
    { name: "Échallens", slug: "flughafentransfer-echallens" },
    { name: "Leysin", slug: "flughafentransfer-leysin" },
    { name: "Bex", slug: "flughafentransfer-bex" },
    { name: "Château-d'Oex", slug: "flughafentransfer-chateau-d-oex" },
  ] },
  { key: "wallis", label: { de: "Kanton Wallis", en: "Canton of Valais" }, cities: [
    { name: "Sion", slug: "flughafentransfer-sion", routeSlug: "zurich-airport-to-sion" },
    { name: "Sierre", slug: "flughafentransfer-sierre" },
    { name: "Martigny", slug: "flughafentransfer-martigny" },
    { name: "Monthey", slug: "flughafentransfer-monthey" },
    { name: "Brig", slug: "flughafentransfer-brig" },
    { name: "Visp", slug: "flughafentransfer-visp" },
    { name: "Verbier", slug: "flughafentransfer-verbier", routeSlug: "zurich-airport-to-verbier" },
    { name: "Crans-Montana", slug: "flughafentransfer-crans-montana" },
    { name: "Saas-Fee", slug: "flughafentransfer-saas-fee" },
    { name: "Leukerbad", slug: "flughafentransfer-leukerbad" },
    { name: "Nendaz", slug: "flughafentransfer-nendaz" },
    { name: "Saillon", slug: "flughafentransfer-saillon" },
    { name: "Fully", slug: "flughafentransfer-fully" },
    { name: "Naters", slug: "flughafentransfer-naters" },
    { name: "Grächen", slug: "flughafentransfer-graechen" },
    { name: "Champéry", slug: "flughafentransfer-champery" },
  ] },
  { key: "neuenburg", label: { de: "Kanton Neuenburg", en: "Canton of Neuchâtel" }, cities: [
    { name: "Neuchâtel", slug: "flughafentransfer-neuchatel" },
    { name: "La Chaux-de-Fonds", slug: "flughafentransfer-la-chaux-de-fonds" },
    { name: "Le Locle", slug: "flughafentransfer-le-locle" },
    { name: "Boudry", slug: "flughafentransfer-boudry" },
    { name: "Peseux", slug: "flughafentransfer-peseux" },
    { name: "Colombier", slug: "flughafentransfer-colombier" },
    { name: "Fleurier", slug: "flughafentransfer-fleurier" },
    { name: "Val-de-Travers", slug: "flughafentransfer-val-de-travers" },
    { name: "Cortaillod", slug: "flughafentransfer-cortaillod" },
  ] },
  { key: "genf", label: { de: "Kanton Genf", en: "Canton of Geneva" }, cities: [
    { name: "Carouge", slug: "flughafentransfer-carouge" },
    { name: "Vernier", slug: "flughafentransfer-vernier" },
    { name: "Lancy", slug: "flughafentransfer-lancy" },
    { name: "Meyrin", slug: "flughafentransfer-meyrin" },
    { name: "Onex", slug: "flughafentransfer-onex" },
    { name: "Thônex", slug: "flughafentransfer-thonex" },
    { name: "Versoix", slug: "flughafentransfer-versoix" },
    { name: "Plan-les-Ouates", slug: "flughafentransfer-plan-les-ouates" },
    { name: "Grand-Saconnex", slug: "flughafentransfer-grand-saconnex" },
    { name: "Cologny", slug: "flughafentransfer-cologny" },
  ] },
  { key: "jura", label: { de: "Kanton Jura", en: "Canton of Jura" }, cities: [
    { name: "Delémont", slug: "flughafentransfer-delemont" },
    { name: "Porrentruy", slug: "flughafentransfer-porrentruy" },
    { name: "Saignelégier", slug: "flughafentransfer-saignelegier" },
    { name: "Bassecourt", slug: "flughafentransfer-bassecourt" },
    { name: "Courrendlin", slug: "flughafentransfer-courrendlin" },
    { name: "Courroux", slug: "flughafentransfer-courroux" },
    { name: "Les Breuleux", slug: "flughafentransfer-les-breuleux" },
  ] },
  { key: "hubs", label: { de: "Flughäfen & Bahnhöfe", en: "Airports & stations" }, cities: [
    { name: "Flughafen Genf (GVA)", slug: "flughafentransfer-flughafen-genf-gva" },
    { name: "EuroAirport Basel", slug: "flughafentransfer-euroairport-basel" },
    { name: "Flughafen Bern-Belp", slug: "flughafentransfer-flughafen-bern-belp" },
    { name: "Flughafen Lugano", slug: "flughafentransfer-flughafen-lugano" },
    { name: "Zürich HB", slug: "flughafentransfer-zuerich-hb" },
    { name: "Bern HB", slug: "flughafentransfer-bern-hb" },
    { name: "Basel SBB", slug: "flughafentransfer-basel-sbb" },
    { name: "Genève-Cornavin", slug: "flughafentransfer-geneve-cornavin" },
    { name: "Lausanne Gare", slug: "flughafentransfer-lausanne-gare" },
  ] },
  { key: "nachbar", label: { de: "Grenzregion & Nachbarländer", en: "Border region & neighbours" }, cities: [
    { name: "Vaduz (FL)", slug: "flughafentransfer-vaduz-fl" },
    { name: "Schaan (FL)", slug: "flughafentransfer-schaan-fl" },
    { name: "Konstanz (DE)", slug: "flughafentransfer-konstanz-de" },
    { name: "Lörrach (DE)", slug: "flughafentransfer-loerrach-de" },
    { name: "Weil am Rhein (DE)", slug: "flughafentransfer-weil-am-rhein-de" },
    { name: "Freiburg im Breisgau (DE)", slug: "flughafentransfer-freiburg-im-breisgau-de" },
    { name: "Friedrichshafen (DE)", slug: "flughafentransfer-friedrichshafen-de" },
    { name: "München (DE)", slug: "flughafentransfer-muenchen-de" },
    { name: "Stuttgart (DE)", slug: "flughafentransfer-stuttgart-de" },
    { name: "Feldkirch (AT)", slug: "flughafentransfer-feldkirch-at" },
    { name: "Bregenz (AT)", slug: "flughafentransfer-bregenz-at" },
    { name: "Innsbruck (AT)", slug: "flughafentransfer-innsbruck-at" },
    { name: "Como (IT)", slug: "flughafentransfer-como-it" },
    { name: "Mailand (IT)", slug: "flughafentransfer-mailand-it" },
    { name: "Milano Malpensa (IT)", slug: "flughafentransfer-milano-malpensa-it" },
    { name: "Varese (IT)", slug: "flughafentransfer-varese-it" },
    { name: "Domodossola (IT)", slug: "flughafentransfer-domodossola-it" },
    { name: "Chamonix (FR)", slug: "flughafentransfer-chamonix-fr" },
    { name: "Annecy (FR)", slug: "flughafentransfer-annecy-fr" },
    { name: "Mulhouse (FR)", slug: "flughafentransfer-mulhouse-fr" },
    { name: "Colmar (FR)", slug: "flughafentransfer-colmar-fr" },
    { name: "Strassburg (FR)", slug: "flughafentransfer-strassburg-fr" },
    { name: "Lyon (FR)", slug: "flughafentransfer-lyon-fr" },
  ] },
];

// Slug → destinasyon (+bölge) hızlı erişim
const index = new Map<string, { d: Destination; region: DestRegion }>();
for (const region of destRegions) for (const d of region.cities) if (!index.has(d.slug)) index.set(d.slug, { d, region });

export const findDestination = (slug: string) => index.get(slug) ?? null;
export const allDestinationSlugs = () => [...index.keys()];
