// ─────────────────────────────────────────────────────────────
//  YASAL SAYFALAR — Datenschutz, Cookie-Richtlinie, AGB, Rückerstattung, Impressum
//  Gövde satırları: "## Başlık" → ara başlık, "[[cookie-settings]]" → çerez ayarları düğmesi,
//  diğer satırlar paragraf. Şirket bilgileri config.ts'ten.
//  Not: Bu metinler İsviçre DSG (revDSG 2023) ve UWG Art. 3 lit. s'ye göre hazırlanmış
//  şablondur; hukuki bağlayıcılık için bir avukat kontrolü önerilir.
// ─────────────────────────────────────────────────────────────
import { COMPANY_NAME, COMPANY_REG, COMPANY_ADDRESS, CONTACT_EMAIL, PHONE_DISPLAY } from "./config";

export type LegalKey = "datenschutz" | "cookies" | "agb" | "rueckerstattung" | "impressum";

const UPDATED_DE = "Stand: September 2026";
const UPDATED_EN = "Last updated: September 2026";

export const legalPages: Record<
  LegalKey,
  { de: { title: string; body: string[] }; en: { title: string; body: string[] } }
> = {
  // ── Impressum ─────────────────────────────────────────────
  impressum: {
    de: {
      title: "Impressum",
      body: [
        "## Anbieterin dieser Website",
        `ZRH Airport Taxi – ${COMPANY_NAME}`,
        COMPANY_ADDRESS,
        `Telefon / WhatsApp: ${PHONE_DISPLAY}`,
        `E-Mail: ${CONTACT_EMAIL}`,
        COMPANY_REG,
        "## Verantwortlich für den Inhalt",
        `${COMPANY_NAME}, Kloten. Der Inhalt dieser Website wurde mit grösstmöglicher Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte übernehmen wir keine Gewähr.`,
        "## Haftungsausschluss",
        "Haftungsansprüche gegen die Anbieterin wegen Schäden materieller oder immaterieller Art, die aus dem Zugriff oder der Nutzung bzw. Nichtnutzung der veröffentlichten Informationen, durch Missbrauch der Verbindung oder durch technische Störungen entstanden sind, werden ausgeschlossen. Verweise und Links auf Websites Dritter liegen ausserhalb unseres Verantwortungsbereichs.",
        "## Urheberrechte",
        "Die Urheber- und alle anderen Rechte an Inhalten, Bildern, Fotos oder anderen Dateien auf dieser Website gehören ausschliesslich der Anbieterin oder den speziell genannten Rechtsinhabern. Für die Reproduktion jeglicher Elemente ist die schriftliche Zustimmung der Urheberrechtsträger im Voraus einzuholen.",
        "## Anwendbares Recht",
        "Es gilt Schweizer Recht. Gerichtsstand ist Kloten, Kanton Zürich, soweit gesetzlich zulässig.",
        UPDATED_DE,
      ],
    },
    en: {
      title: "Imprint",
      body: [
        "## Provider of this website",
        `ZRH Airport Taxi – ${COMPANY_NAME}`,
        COMPANY_ADDRESS,
        `Phone / WhatsApp: ${PHONE_DISPLAY}`,
        `Email: ${CONTACT_EMAIL}`,
        `Commercial register no.: ${COMPANY_REG.replace("Handelsregister-Nr.: ", "")}`,
        "## Responsible for content",
        `${COMPANY_NAME}, Kloten. The content of this website has been prepared with the greatest possible care. We accept no liability for the accuracy, completeness or timeliness of the content.`,
        "## Disclaimer",
        "Liability claims against the provider for material or immaterial damage arising from access to or use or non-use of the published information, from misuse of the connection or from technical faults are excluded. References and links to third-party websites are outside our area of responsibility.",
        "## Copyright",
        "Copyright and all other rights to content, images, photos or other files on this website belong exclusively to the provider or the specifically named rights holders. Written consent of the copyright holders must be obtained in advance for the reproduction of any elements.",
        "## Applicable law",
        "Swiss law applies. Place of jurisdiction is Kloten, Canton of Zurich, to the extent permitted by law.",
        UPDATED_EN,
      ],
    },
  },

  // ── Datenschutz ───────────────────────────────────────────
  datenschutz: {
    de: {
      title: "Datenschutzerklärung",
      body: [
        `Der Schutz Ihrer persönlichen Daten ist uns wichtig. Diese Datenschutzerklärung erläutert, welche Personendaten ZRH Airport Taxi (${COMPANY_NAME}, ${COMPANY_ADDRESS}) beim Besuch dieser Website und bei der Buchung eines Transfers bearbeitet, zu welchem Zweck und auf welcher Grundlage. Massgebend ist das Schweizer Datenschutzgesetz (DSG); soweit anwendbar, beachten wir zusätzlich die Datenschutz-Grundverordnung (DSGVO) der EU.`,
        "## 1. Verantwortliche Stelle",
        `${COMPANY_NAME}, ${COMPANY_ADDRESS}, E-Mail ${CONTACT_EMAIL}, Telefon ${PHONE_DISPLAY}. Bei Fragen zum Datenschutz oder zur Ausübung Ihrer Rechte wenden Sie sich bitte an diese Adresse.`,
        "## 2. Welche Daten wir bei einer Buchung bearbeiten",
        "Zur Abwicklung Ihres Transfers erfassen wir: Vor- und Nachname, E-Mail-Adresse, Telefonnummer, Abhol- und Zieladresse, Datum und Uhrzeit, Flugnummer, Anzahl Personen und Gepäck, gewünschte Fahrzeugklasse, Kindersitze, allfällige Bemerkungen sowie die von Ihnen gewählte Sprache. Diese Daten sind für die Erbringung der Leistung erforderlich (Vertragserfüllung).",
        "Zusätzlich speichern wir technische Daten der Buchung: Zeitpunkt, Buchungsreferenz, Zahlungsstatus und – zur Betrugsprävention und Nachvollziehbarkeit – die IP-Adresse und den Browsertyp, mit dem die Buchung abgeschickt wurde.",
        "## 3. Zahlungsabwicklung (Stripe)",
        "Online-Zahlungen wickeln wir über Stripe Payments Europe Ltd. (Irland) ab. Ihre Kartendaten werden direkt bei Stripe eingegeben und verarbeitet; wir erhalten keine vollständigen Kartendaten, sondern nur eine Zahlungsreferenz, den Betrag und den Status. Stripe kann Daten auch in die USA übermitteln; es bestehen die von Stripe vorgesehenen Garantien (EU-Standardvertragsklauseln). Weitere Informationen: stripe.com/privacy.",
        "## 4. Weitergabe an Dritte und Auftragsbearbeiter",
        "Ihre Buchungsdaten werden an den für Ihre Fahrt eingeteilten Chauffeur weitergegeben (Name, Telefonnummer, Adressen, Zeiten, Flugnummer, Bemerkungen). Zur Disposition tragen wir bestätigte Fahrten in einen Google-Kalender (Google Ireland Ltd.) ein. Für den E-Mail-Versand von Bestätigungen nutzen wir Google Workspace. Die Website wird von Vercel Inc. (USA) gehostet; die Buchungsdatenbank wird von Supabase Inc. betrieben, Serverstandort EU. Alle Dienstleister sind vertraglich zur Vertraulichkeit und zum Datenschutz verpflichtet. Wir verkaufen keine Daten an Dritte.",
        "## 5. Statistik und Marketing (nur mit Ihrer Einwilligung)",
        "Beim ersten Besuch fragen wir Sie über ein Cookie-Banner, ob Sie Statistik- und Marketing-Diensten zustimmen. Ohne Ihre Einwilligung werden keine entsprechenden Cookies gesetzt und keine personenbezogenen Kennungen übermittelt. Sie können Ihre Auswahl jederzeit über den Link «Cookie-Einstellungen» in der Fusszeile ändern.",
        "Google Tag Manager (Google Ireland Ltd.) dient als technisches Werkzeug zur Verwaltung der nachfolgenden Dienste; er setzt selbst keine Analyse-Cookies.",
        "Google Analytics 4 (Statistik): Erfasst anonymisierte Nutzungsstatistiken (aufgerufene Seiten, Verweildauer, ungefähre Herkunft, Buchungsschritte). IP-Adressen werden gekürzt verarbeitet. Bei Einwilligung übermitteln wir zudem serverseitig Ereignisse wie «Buchung bestätigt» mit einer pseudonymen Client-Kennung, damit Statistiken vollständig sind. Google kann Daten in die USA übermitteln (Standardvertragsklauseln, Data Privacy Framework).",
        "Google Ads (Marketing): Misst, ob Besucher über eine Google-Anzeige zu uns gekommen sind, und ermöglicht Conversion-Messung. Ohne Marketing-Einwilligung werden keine Werbe-Cookies gesetzt; Google erhält dann lediglich cookielose, aggregierte Signale (Consent Mode).",
        "Meta Pixel und Conversions API (Marketing): Bei Marketing-Einwilligung setzen wir das Meta-Pixel (Meta Platforms Ireland Ltd.) ein und übermitteln bestätigte Buchungen serverseitig an Meta, um die Wirksamkeit von Anzeigen auf Facebook und Instagram zu messen. Kontaktdaten werden dabei ausschliesslich in gehashter (unlesbarer) Form übermittelt.",
        "## 6. Cookies",
        "Details zu den eingesetzten Cookies, ihren Zwecken und Laufzeiten finden Sie in unserer Cookie-Richtlinie.",
        "## 7. Server-Logdaten und Besucherstatistik",
        "Beim Aufruf der Website verarbeitet der Hosting-Anbieter technisch notwendige Verbindungsdaten (IP-Adresse, Zeitpunkt, aufgerufene Seite, Browser) in Server-Logs zur Gewährleistung des Betriebs und der Sicherheit. Für unsere interne Besucherstatistik speichern wir nur Land und Stadt der Anfrage – ohne IP-Adresse.",
        "## 8. Kontaktformular, WhatsApp und E-Mail",
        "Anfragen über das Kontaktformular werden mit Name, E-Mail, Telefon und Nachricht gespeichert, um sie beantworten zu können. Bei Kontakt über WhatsApp gelten zusätzlich die Datenschutzbestimmungen von WhatsApp Ireland Ltd.",
        "## 9. Aufbewahrung",
        "Buchungs- und Rechnungsdaten bewahren wir gemäss den gesetzlichen Aufbewahrungspflichten (Obligationenrecht) während zehn Jahren auf. Kontaktanfragen löschen wir spätestens zwei Jahre nach Abschluss. Statistikdaten werden nach den Standardfristen der jeweiligen Anbieter gelöscht.",
        "## 10. Ihre Rechte",
        "Sie haben das Recht auf Auskunft über Ihre bei uns gespeicherten Personendaten, auf Berichtigung, Löschung, Einschränkung der Bearbeitung und Datenübertragung sowie das Recht, eine erteilte Einwilligung jederzeit zu widerrufen. Wenden Sie sich dazu an die oben genannte Adresse. Sie haben zudem das Recht, sich beim Eidgenössischen Datenschutz- und Öffentlichkeitsbeauftragten (EDÖB) zu beschweren.",
        "## 11. Änderungen",
        "Wir können diese Datenschutzerklärung jederzeit anpassen. Es gilt die jeweils auf dieser Seite veröffentlichte Fassung.",
        UPDATED_DE,
      ],
    },
    en: {
      title: "Privacy Policy",
      body: [
        `Protecting your personal data matters to us. This privacy policy explains which personal data ZRH Airport Taxi (${COMPANY_NAME}, ${COMPANY_ADDRESS}) processes when you visit this website and book a transfer, for what purpose and on what basis. The Swiss Federal Act on Data Protection (FADP) applies; where applicable, we additionally observe the EU General Data Protection Regulation (GDPR).`,
        "## 1. Controller",
        `${COMPANY_NAME}, ${COMPANY_ADDRESS}, email ${CONTACT_EMAIL}, phone ${PHONE_DISPLAY}. For questions about data protection or to exercise your rights, please contact this address.`,
        "## 2. Data we process for a booking",
        "To provide your transfer we collect: first and last name, email address, phone number, pickup and destination address, date and time, flight number, number of passengers and luggage, chosen vehicle class, child seats, any remarks and the language you selected. This data is necessary to perform the service (contract fulfilment).",
        "We additionally store technical booking data: timestamp, booking reference, payment status and – for fraud prevention and traceability – the IP address and browser type used to submit the booking.",
        "## 3. Payment processing (Stripe)",
        "Online payments are processed by Stripe Payments Europe Ltd. (Ireland). Your card details are entered and processed directly with Stripe; we do not receive full card data, only a payment reference, the amount and the status. Stripe may transfer data to the USA under the safeguards it provides (EU standard contractual clauses). More information: stripe.com/privacy.",
        "## 4. Disclosure to third parties and processors",
        "Your booking data is passed to the chauffeur assigned to your journey (name, phone number, addresses, times, flight number, remarks). For dispatching we enter confirmed journeys in a Google Calendar (Google Ireland Ltd.). Confirmation emails are sent via Google Workspace. The website is hosted by Vercel Inc. (USA); the booking database is operated by Supabase Inc. on servers in the EU. All service providers are contractually bound to confidentiality and data protection. We do not sell data to third parties.",
        "## 5. Statistics and marketing (only with your consent)",
        "On your first visit a cookie banner asks whether you consent to statistics and marketing services. Without your consent no such cookies are set and no personal identifiers are transmitted. You can change your selection at any time via the \"Cookie settings\" link in the footer.",
        "Google Tag Manager (Google Ireland Ltd.) is a technical tool for managing the services below; it does not set analytics cookies itself.",
        "Google Analytics 4 (statistics): collects anonymised usage statistics (pages viewed, time on site, approximate origin, booking steps). IP addresses are processed in truncated form. With consent we additionally transmit events such as \"booking confirmed\" server-side with a pseudonymous client identifier so that statistics are complete. Google may transfer data to the USA (standard contractual clauses, Data Privacy Framework).",
        "Google Ads (marketing): measures whether visitors reached us via a Google ad and enables conversion measurement. Without marketing consent no advertising cookies are set; Google then only receives cookieless, aggregated signals (Consent Mode).",
        "Meta Pixel and Conversions API (marketing): with marketing consent we use the Meta Pixel (Meta Platforms Ireland Ltd.) and transmit confirmed bookings server-side to Meta to measure the effectiveness of ads on Facebook and Instagram. Contact data is transmitted exclusively in hashed (unreadable) form.",
        "## 6. Cookies",
        "Details of the cookies used, their purposes and lifetimes can be found in our cookie policy.",
        "## 7. Server logs and visitor statistics",
        "When the website is accessed, the hosting provider processes technically necessary connection data (IP address, time, page requested, browser) in server logs to ensure operation and security. For our internal visitor statistics we store only the country and city of the request – without the IP address.",
        "## 8. Contact form, WhatsApp and email",
        "Enquiries via the contact form are stored with name, email, phone and message so that we can answer them. When you contact us via WhatsApp, the privacy terms of WhatsApp Ireland Ltd. additionally apply.",
        "## 9. Retention",
        "We retain booking and invoice data for ten years in accordance with statutory retention obligations (Swiss Code of Obligations). Contact enquiries are deleted no later than two years after completion. Statistics data is deleted according to the standard retention periods of the respective providers.",
        "## 10. Your rights",
        "You have the right to information about the personal data we hold about you, to rectification, erasure, restriction of processing and data portability, and the right to withdraw consent at any time. Please contact the address above. You also have the right to lodge a complaint with the Swiss Federal Data Protection and Information Commissioner (FDPIC).",
        "## 11. Changes",
        "We may amend this privacy policy at any time. The version published on this page applies.",
        UPDATED_EN,
      ],
    },
  },

  // ── Cookie-Richtlinie ─────────────────────────────────────
  cookies: {
    de: {
      title: "Cookie-Richtlinie",
      body: [
        "Cookies sind kleine Textdateien, die Ihr Browser speichert, damit eine Website Sie wiedererkennen kann. Wir setzen technisch notwendige Cookies ohne Ihre Einwilligung ein; Statistik- und Marketing-Cookies nur, wenn Sie ihnen im Cookie-Banner zugestimmt haben.",
        "## Ihre Auswahl ändern",
        "Sie können Ihre Einwilligung jederzeit anpassen oder widerrufen:",
        "[[cookie-settings]]",
        "## 1. Notwendige Cookies (immer aktiv)",
        "zrh_consent – speichert Ihre Cookie-Auswahl, damit das Banner nicht bei jedem Besuch erscheint. Laufzeit: 180 Tage. Anbieterin: ZRH Airport Taxi.",
        "Sitzungs-Cookies des Buchungsprozesses und der Zahlungsseite (Stripe) – erforderlich, damit Ihre Buchung und Zahlung technisch abgewickelt werden können. Laufzeit: Sitzung bzw. gemäss Stripe.",
        "## 2. Statistik-Cookies (nur mit Einwilligung)",
        "_ga, _ga_* – Google Analytics 4 (Google Ireland Ltd.). Unterscheidet Besucher pseudonym und misst Seitenaufrufe, Verweildauer und Buchungsschritte. Laufzeit: bis zu 2 Jahre.",
        "## 3. Marketing-Cookies (nur mit Einwilligung)",
        "_gcl_au, _gcl_aw und weitere Google-Ads-Cookies – Google Ireland Ltd. Messen, ob ein Besuch oder eine Buchung auf eine Google-Anzeige zurückgeht. Laufzeit: bis zu 90 Tage.",
        "_fbp, _fbc – Meta Platforms Ireland Ltd. (Meta Pixel). Messen die Wirksamkeit von Anzeigen auf Facebook und Instagram. Laufzeit: bis zu 90 Tage.",
        "## 4. Cookies von eingebetteten Diensten",
        "Eingebettete Inhalte wie Google Maps oder die Stripe-Zahlungsseite können eigene Cookies verwenden; dafür gilt die Datenschutzerklärung des jeweiligen Anbieters.",
        "## 5. Cookies im Browser löschen",
        "Unabhängig von unserem Banner können Sie Cookies jederzeit in den Einstellungen Ihres Browsers einsehen, löschen oder blockieren. Werden notwendige Cookies blockiert, funktionieren Buchung und Zahlung unter Umständen nicht.",
        "Weitere Informationen zur Bearbeitung Ihrer Daten finden Sie in unserer Datenschutzerklärung.",
        UPDATED_DE,
      ],
    },
    en: {
      title: "Cookie Policy",
      body: [
        "Cookies are small text files stored by your browser so that a website can recognise you. We use technically necessary cookies without your consent; statistics and marketing cookies only if you have agreed to them in the cookie banner.",
        "## Change your selection",
        "You can adjust or withdraw your consent at any time:",
        "[[cookie-settings]]",
        "## 1. Necessary cookies (always active)",
        "zrh_consent – stores your cookie selection so the banner does not appear on every visit. Lifetime: 180 days. Provider: ZRH Airport Taxi.",
        "Session cookies of the booking process and the payment page (Stripe) – required so that your booking and payment can be processed technically. Lifetime: session or as per Stripe.",
        "## 2. Statistics cookies (with consent only)",
        "_ga, _ga_* – Google Analytics 4 (Google Ireland Ltd.). Distinguishes visitors pseudonymously and measures page views, time on site and booking steps. Lifetime: up to 2 years.",
        "## 3. Marketing cookies (with consent only)",
        "_gcl_au, _gcl_aw and other Google Ads cookies – Google Ireland Ltd. Measure whether a visit or booking originated from a Google ad. Lifetime: up to 90 days.",
        "_fbp, _fbc – Meta Platforms Ireland Ltd. (Meta Pixel). Measure the effectiveness of ads on Facebook and Instagram. Lifetime: up to 90 days.",
        "## 4. Cookies from embedded services",
        "Embedded content such as Google Maps or the Stripe payment page may use its own cookies; the respective provider's privacy policy applies.",
        "## 5. Deleting cookies in your browser",
        "Independently of our banner, you can view, delete or block cookies at any time in your browser settings. If necessary cookies are blocked, booking and payment may not work.",
        "Further information on how we process your data is available in our privacy policy.",
        UPDATED_EN,
      ],
    },
  },

  // ── AGB ───────────────────────────────────────────────────
  agb: {
    de: {
      title: "Allgemeine Geschäftsbedingungen (AGB)",
      body: [
        `Diese Allgemeinen Geschäftsbedingungen regeln die Buchung und Durchführung von Personentransporten durch ZRH Airport Taxi (${COMPANY_NAME}, ${COMPANY_ADDRESS}), nachfolgend «wir». Mit dem Abschluss einer Buchung akzeptieren Sie diese Bedingungen.`,
        "## 1. Leistung",
        "Wir erbringen private Transfers mit Chauffeur zwischen dem Flughafen Zürich und Zielen in der Schweiz sowie im angrenzenden Ausland, zu den auf der Website ausgewiesenen Festpreisen oder zu einem individuell bestätigten Preis. Zur Leistung gehören Meet & Greet in der Ankunftshalle mit Namensschild, Flugverfolgung, 60 Minuten Wartezeit nach der tatsächlichen Landung, Hilfe mit dem Gepäck sowie auf Anmeldung Kindersitze ohne Aufpreis.",
        "## 2. Buchung und Vertragsschluss",
        "Eine Buchung über die Website ist ein Angebot Ihrerseits. Der Vertrag kommt zustande, wenn wir die Buchung per E-Mail bestätigen. Bis zur Bestätigung ist die Buchung eine Anfrage; lehnen wir sie ab (z. B. wegen fehlender Verfügbarkeit), wird eine bereits geleistete Zahlung vollständig zurückerstattet. Anfragen, die zwischen 23:00 und 06:00 Uhr eingehen und innerhalb der nächsten zwei Stunden starten sollen, können online nicht angenommen werden.",
        "## 3. Preise und Zahlung",
        "Alle Preise verstehen sich in Schweizer Franken pro Fahrzeug, inklusive Mehrwertsteuer, für die gebuchte Strecke und die angegebene Personen- und Gepäckzahl. Zwischen 00:00 und 06:00 Uhr gilt ein Nachttarif (Transfers +20 %, Stundenbuchungen +30 %), der bei der Buchung im angezeigten Preis enthalten ist; Wochenend- oder Feiertagszuschläge gibt es nicht. Die Zahlung erfolgt bei der Buchung online per Karte über unseren Zahlungsdienstleister Stripe. Für Firmenkunden und Sonderfahrten sind nach Absprache andere Zahlungsarten möglich. Sie erhalten für jede Fahrt eine Rechnung mit ausgewiesener Mehrwertsteuer.",
        "Zusätzliche, nicht gebuchte Leistungen (zusätzliche Zwischenhalte, Wartezeit über die inkludierte Zeit hinaus, wesentliche Routenänderungen auf Ihren Wunsch) werden vorgängig angekündigt und separat verrechnet.",
        "## 4. Stornierung und Änderung",
        "Bis 24 Stunden vor der vereinbarten Abholzeit können Sie kostenlos stornieren; eine geleistete Zahlung wird vollständig zurückerstattet. Bei Stornierung innerhalb von 24 Stunden oder bei Nichterscheinen (No-Show) kann der volle Fahrpreis geschuldet sein. Änderungen von Zeit, Adresse oder Fahrzeugklasse sind bis 24 Stunden vor der Abholung nach Verfügbarkeit kostenlos möglich. Einzelheiten regelt unsere Rückerstattungsrichtlinie.",
        "## 5. Flugverspätung und Nichterscheinen",
        "Bei Abholungen am Flughafen richtet sich die Abholzeit nach der tatsächlichen Landezeit des angegebenen Fluges. Eine Flugverspätung verursacht keine Zusatzkosten. Erscheinen Sie ohne Mitteilung nicht innerhalb von 60 Minuten nach der Landung am Treffpunkt und sind Sie telefonisch nicht erreichbar, gilt die Fahrt als nicht angetreten. Bei Abholungen an einer Adresse wartet der Chauffeur 15 Minuten ab der vereinbarten Zeit.",
        "## 6. Ihre Mitwirkung",
        "Bitte geben Sie bei der Buchung vollständige und korrekte Angaben, insbesondere Flugnummer, Telefonnummer, Personen- und Gepäckzahl sowie Kinder mit Alter. Gepäck, das die Kapazität der gebuchten Fahrzeugklasse übersteigt, kann nur nach Verfügbarkeit befördert werden. Im Fahrzeug gilt Rauchverbot; Verschmutzungen oder Beschädigungen, die über die normale Nutzung hinausgehen, werden zum Selbstkostenpreis verrechnet.",
        "## 7. Haftung",
        "Wir haften für Schäden, die wir oder unsere Chauffeure vorsätzlich oder grobfahrlässig verursachen, sowie nach den zwingenden Bestimmungen des Strassenverkehrsgesetzes. Für verpasste Flüge oder Anschlüsse infolge von Umständen, die ausserhalb unseres Einflusses liegen (Verkehr, Wetter, Strassensperrungen, höhere Gewalt), übernehmen wir keine Haftung; wir planen jedoch stets mit angemessenem Zeitpuffer. Für im Fahrzeug vergessene Gegenstände haften wir nicht, bewahren gefundene Gegenstände jedoch auf und geben sie zurück.",
        "## 8. Datenschutz",
        "Die Bearbeitung Ihrer Personendaten ist in unserer Datenschutzerklärung beschrieben.",
        "## 9. Schlussbestimmungen",
        "Sollten einzelne Bestimmungen dieser AGB unwirksam sein, bleibt die Wirksamkeit der übrigen Bestimmungen unberührt. Es gilt Schweizer Recht; Gerichtsstand ist Kloten, Kanton Zürich, soweit gesetzlich zulässig.",
        UPDATED_DE,
      ],
    },
    en: {
      title: "Terms and Conditions",
      body: [
        `These terms and conditions govern the booking and provision of passenger transport by ZRH Airport Taxi (${COMPANY_NAME}, ${COMPANY_ADDRESS}), hereinafter "we". By completing a booking you accept these terms.`,
        "## 1. Service",
        "We provide private chauffeur-driven transfers between Zurich Airport and destinations in Switzerland and neighbouring countries at the fixed prices shown on the website or at an individually confirmed price. The service includes meet & greet in the arrivals hall with a name sign, flight tracking, 60 minutes of waiting time after the actual landing, help with luggage and, on request, child seats at no extra charge.",
        "## 2. Booking and contract",
        "A booking via the website is an offer on your part. The contract is concluded when we confirm the booking by email. Until confirmation the booking is a request; if we decline it (e.g. due to lack of availability), any payment already made is refunded in full. Requests received between 11 pm and 6 am for journeys due to start within the next two hours cannot be accepted online.",
        "## 3. Prices and payment",
        "All prices are in Swiss francs per vehicle, including VAT, for the booked route and the stated number of passengers and luggage. Between midnight and 6 am a night tariff applies (transfers +20 %, hourly bookings +30 %), included in the price shown at booking; there are no weekend or public-holiday surcharges. Payment is made online by card at the time of booking via our payment provider Stripe. Other payment methods are possible for corporate clients and special journeys by arrangement. You receive an invoice with VAT shown for every journey.",
        "Additional services not booked (extra stops, waiting time beyond the included allowance, substantial route changes at your request) are announced in advance and invoiced separately.",
        "## 4. Cancellation and changes",
        "Up to 24 hours before the agreed pickup time you may cancel free of charge; any payment made is refunded in full. For cancellations within 24 hours or in the event of a no-show, the full fare may be due. Changes of time, address or vehicle class are possible free of charge up to 24 hours before pickup, subject to availability. Details are set out in our refund policy.",
        "## 5. Flight delays and no-show",
        "For airport pickups, the pickup time follows the actual landing time of the stated flight. A flight delay causes no additional costs. If you do not appear at the meeting point within 60 minutes of landing without notice and cannot be reached by phone, the journey is deemed not taken. For pickups at an address, the chauffeur waits 15 minutes from the agreed time.",
        "## 6. Your cooperation",
        "Please provide complete and correct details when booking, in particular flight number, phone number, number of passengers and luggage, and children with their ages. Luggage exceeding the capacity of the booked vehicle class can only be carried subject to availability. Smoking is not permitted in the vehicle; soiling or damage beyond normal use is charged at cost.",
        "## 7. Liability",
        "We are liable for damage caused intentionally or through gross negligence by us or our chauffeurs, and in accordance with the mandatory provisions of the Swiss Road Traffic Act. We accept no liability for missed flights or connections due to circumstances beyond our control (traffic, weather, road closures, force majeure); we do, however, always plan with a reasonable time buffer. We are not liable for items left in the vehicle, but we keep found items and return them.",
        "## 8. Data protection",
        "The processing of your personal data is described in our privacy policy.",
        "## 9. Final provisions",
        "Should individual provisions of these terms be invalid, the validity of the remaining provisions is unaffected. Swiss law applies; place of jurisdiction is Kloten, Canton of Zurich, to the extent permitted by law.",
        UPDATED_EN,
      ],
    },
  },

  // ── Rückerstattung ────────────────────────────────────────
  rueckerstattung: {
    de: {
      title: "Rückerstattungsrichtlinie",
      body: [
        "Wir möchten, dass Sie mit Sicherheit buchen können. Diese Richtlinie erklärt, wann und wie Sie Ihr Geld zurückerhalten.",
        "## 1. Kostenlose Stornierung bis 24 Stunden vorher",
        "Stornieren Sie bis 24 Stunden vor der vereinbarten Abholzeit, erstatten wir den vollen Betrag. Die Rückerstattung wird automatisch auf das ursprüngliche Zahlungsmittel ausgelöst; je nach Bank ist der Betrag innerhalb von 3 bis 10 Werktagen sichtbar.",
        "## 2. Ablehnung durch uns",
        "Können wir eine Buchungsanfrage nicht annehmen – etwa weil kein Fahrzeug verfügbar ist –, erstatten wir eine bereits geleistete Zahlung sofort und vollständig, unabhängig vom Zeitpunkt.",
        "## 3. Stornierung innerhalb von 24 Stunden",
        "Bei Stornierungen weniger als 24 Stunden vor der Abholung ist der Chauffeur in der Regel bereits eingeteilt. Wir behalten uns vor, den vollen Fahrpreis zu berechnen. Kontaktieren Sie uns in diesem Fall bitte direkt – bei Flugannullierungen, Krankheit oder anderen nachvollziehbaren Gründen finden wir gemeinsam eine faire Lösung, zum Beispiel eine kostenlose Umbuchung oder eine Gutschrift.",
        "## 4. Flugverspätung und Annullierung",
        "Verspätet sich Ihr Flug, passen wir die Abholzeit automatisch an; es entstehen keine Zusatzkosten und keine Stornierung. Wird Ihr Flug annulliert und Sie reisen nicht, gilt Ziffer 1 beziehungsweise – innerhalb von 24 Stunden – Ziffer 3.",
        "## 5. Nichterscheinen (No-Show)",
        "Erscheinen Sie ohne Mitteilung nicht am Treffpunkt und sind Sie nicht erreichbar, ist der volle Fahrpreis geschuldet und wird nicht erstattet. Melden Sie sich daher bitte immer, wenn sich etwas ändert – auch kurzfristig per WhatsApp.",
        "## 6. Änderungen statt Stornierung",
        "Zeit, Adresse und Fahrzeugklasse können Sie bis 24 Stunden vor der Abholung kostenlos ändern, sofern verfügbar. Ergibt sich dadurch ein tieferer Preis, erstatten wir die Differenz; ein höherer Preis wird nachbelastet.",
        "## 7. Wie Sie stornieren",
        `Per E-Mail an ${CONTACT_EMAIL} oder per WhatsApp an ${PHONE_DISPLAY} unter Angabe Ihrer Buchungsreferenz. Sie erhalten eine Bestätigung der Stornierung per E-Mail.`,
        UPDATED_DE,
      ],
    },
    en: {
      title: "Refund Policy",
      body: [
        "We want you to book with confidence. This policy explains when and how you get your money back.",
        "## 1. Free cancellation up to 24 hours before",
        "If you cancel up to 24 hours before the agreed pickup time, we refund the full amount. The refund is triggered automatically to the original payment method; depending on your bank, the amount is visible within 3 to 10 business days.",
        "## 2. Declined by us",
        "If we cannot accept a booking request – for instance because no vehicle is available – we refund any payment already made immediately and in full, regardless of timing.",
        "## 3. Cancellation within 24 hours",
        "For cancellations less than 24 hours before pickup, the chauffeur has usually already been assigned. We reserve the right to charge the full fare. In this case please contact us directly – for flight cancellations, illness or other understandable reasons we find a fair solution together, for example a free rebooking or a credit note.",
        "## 4. Flight delay and cancellation",
        "If your flight is delayed, we adjust the pickup time automatically; there are no additional costs and no cancellation. If your flight is cancelled and you do not travel, section 1 applies or – within 24 hours – section 3.",
        "## 5. No-show",
        "If you do not appear at the meeting point without notice and cannot be reached, the full fare is due and is not refunded. Please always let us know when something changes – even at short notice via WhatsApp.",
        "## 6. Changes instead of cancellation",
        "You can change time, address and vehicle class free of charge up to 24 hours before pickup, subject to availability. If this results in a lower price, we refund the difference; a higher price is charged additionally.",
        "## 7. How to cancel",
        `By email to ${CONTACT_EMAIL} or via WhatsApp to ${PHONE_DISPLAY}, stating your booking reference. You receive a cancellation confirmation by email.`,
        UPDATED_EN,
      ],
    },
  },
};
